### ISSUE TITLE
New Doc Proposal - Safe Harbor

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1045]
Document Pantheon's position on Safe Harbor.

Users in the EU have been asking about the implications of the Safe Harbor ruling. It would be good to get a doc page or notice out. A doc page may be easiest.

[Google Compute example](https://www.evernote.com/shard/s390/sh/7c4ae221-f5db-40d9-a132-ee82972671be/2f321c4cf6ea670621f3a189123c0ab5)

Ticket #47304

Migrated from sprintly, originally created by @timani - point of contact for review/triage is @garydylina

**Comment by joshkoenig** [comment]
I would suggest a simpler document that explains "where are Pantheon's Servers". This has a definitive answer and does not involve a legal opinion.

**Comment by joshkoenig** [comment]
Ping @garydylina - do you have any concerns with the above kind of doc?

**Comment by garydylina** [comment]
@joshkoenig I definitely have concerns about creating such a document because, as you suggest, there may be legal implications if our statement isn't perfectly accurate. Matt Stodolnic and I agreed yesterday to pull together a statement as a blog post that can be used by sales to answer questions on this topic.  The result of that effort may be a good starting point for a document here.  In some cases, saying less is actually better.

**Comment by bmackinney** [comment]
Closing in favor of a section in `/sites` or as a page `/sites/architecture`
