### ISSUE TITLE
Drupal Drush Command-Line Utility Doc Update 

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/documentation#1203]
Re: [Drupal Drush Command-Line Utility](https://pantheon.io/docs/articles/local/drupal-drush-command-line-utility)
## Suggested Resolution 

- [ ] document the correct use of all working options, sql-sync and sql-sync-pipe alike

**Comment by greg-1-anderson** [comment]
sql-sync-pipe results in an empty target database.

Drush sql-dump piped to drush sql-connect is already documented with complete options.

Drush sql-sync can be used with default options, e.g. `drush sql-sync @pantheon.mysite.dev @pantheon.myothersite.dev` works fine.

**Comment by colans** [comment]
@greg-1-anderson : Is it sql-syn-piping to Pantheon that often doesn't work, or from Pantheon?  I've been sql-sync-piping from Pantheon for years, and have never run into this problem.

Looks like the commit for the above is c4ff086cf263b11660bb999b3564692105a5de8d

**Comment by greg-1-anderson** [comment]
My test was run from a remote machine with pantheon source and target. This was from a request that came from support, which probably originated with a customer.

Since sql-sync is working well, and sql-sync-pipe is dangerous in at least some scenarios, I don't think that Pantheon should recommend the use of the later for the time being.

**Comment by greg-1-anderson** [comment]
I should also mention that I only tested using a new site, running Drush 8 locally (HEAD of master required, until Drush 8.0.4 is out), and Drush 8 on the platform.  Existing Pantheon sites will still be using Drush 5, which might work better. YMMV.
