### ISSUE TITLE
Mobile Redirection: New Doc Proposal

### ISSUE THREAD

**Issue by sukottokun** [pantheon-systems/documentation#1367]
## Title
Mobile Redirection

## Outline
1. Responsive
1. CDN Redirection

## Path
(e.g. `source/docs/articles/sites/code` or `source/docs/articles/wordpress`)

**Comment by ioskevich** [comment]
Steps to setup Mobile Redirect on CloudFlare: https://support.cloudflare.com/hc/en-us/articles/200168336-About-CloudFlare-Mobile-Redirect
However, this document seems a bit outdated (CF UI has changed since this guide was written), so here are steps with current UI. Also, the above doc states that Mobile Redirect is available on Paid plans only, which is not true.

**Preconditions:**

1. CloudFlare account
2. DNS for the domain that you need mobile redirect setup for is managed at CLoudFlare (name servers point to it).

**Limitations:**

1. Seems you can set it up only for LIVE domain name - means if you want to test it for DEV or TEST iPantheon instances, you will have to point LIVE domain name to DEV or TEST on Pantheon.

Steps to setup:

1. Go to you CloudFlare account
2. Go to the domain you want to setup mobile redirect for.
3. Click on "Speed" icon on top of the page
4. Scroll down to the Mobile Redirect section
5. Setup as needed
6. Give it a couple of minutes to update
7. Test with your mobile device or emulator: 
  * enter desktop URL in mobile browser
  * you should be redirected to the mobile domain you have chosen.
