### ISSUE TITLE
Performance testing of the compiled site

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/documentation#1411]
## Issue Description

The front-end performance of the docs site could be improved in a couple of ways to speed up page load time. Here is a report on a guide page from sitespeed.io: https://results.sitespeed.io/481f-2016/1/29/995094a0-fd1e-4161-be8e-ffefb3a1ab76/index2.html

## Suggested Resolution

This site should have a concrete performance budget that can be tested with each pull request and tracked over time. I have a start on the mechanism over in https://github.com/stevector/documentation/pull/1 I will move that PR over to the main repo rather than a fork.

There are a couple of key questions to be answered:

- What should be the budget numbers for each metric measured? Or perhaps do we only care about total page load time and don't worry about some single metrics remaining red.
- How do we phase in the testing mechanism? We could set a strict budget and not merge in the testing until the strict budget is completely met. We could see a really easy budget just to get the PR testing merged and then progressively make the budget stricter as the performance is improved. Personally, I'd like to do something in the middle: merge in the testing itself along with whatever are the easiest/biggest fixes. We could then have follow-up issues for more complex/time consuming improvements.
- Can we graph changes over time? Sitespeed can integrate with Grafana but I don't know if it is worth our time to spin-up additional infrastructure.
- What URLs should be tested? sitespeed.io can crawl a site from an arbitrary starting point or it can take an exact set of URLs. I lean toward specifying an exact set of representative URLs.

**Comment by ataylorme** [comment]
> How do we phase in the testing mechanism? ... I'd like to do something in the middle: merge in the testing itself along with whatever are the easiest/biggest fixes. We could then have follow-up issues for more complex/time consuming improvements.

I agree with finding the low hanging fruit for the initial integration. 

I think we should define what these initial items and break them out into separate issues.

For example, concatenation would correct _Number of JS files per page_ and _Number of CSS files per page_. This can be it's own issue.

Once all of the blocking issues are resolved then we run a few test to establish a baseline and merge this in.

> What should be the budget numbers for each metric measured? Or perhaps do we only care about total page load time and don't worry about some single metrics remaining red.

Steve we discussed this briefly yesterday but an alternative approach would be to allow for a certain deviation, such as -5%, and any build that decrease the site speed score more than the allowed difference from the previous test are rejected.

> What URLs should be tested? sitespeed.io can crawl a site from an arbitrary starting point or it can take an exact set of URLs. I lean toward specifying an exact set of representative URLs.

+1 to exact URLs. I think a full crawl would take too long. The [URL in your test above](https://pantheon.io/docs/guides/collaborative-development-github-pantheon/) seems like a good choice since that is a ver image heavy page. Maybe we choose 2-3 heavy pages and 2-3 lighter pages so there is a good mix.

**Comment by stevector** [comment]
Sorry for the delays here. I've had other work take priority. This week I expect to have a PRs that addresses the number of CSS files by concatenating them using grunt.  I may have time to include JS as well. In both cases, I don't expect the to get the number of files down to 1. So far in working with CSS I've gotten all directly referenced CSS files concatenated. But our search widget adds it's own CSS file and I might not be able to do anything there.

**Comment by stevector** [comment]
The PR is #1416 now takes a list of urls.
