### ISSUE TITLE
April Changelog Candidates

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#1422]

**Comment by kibra** [comment]
Hi Natalie,

I put an update in here last month, but I don't think it made it into the docs.

The behaviour around vanity domains changed a little. On [this](https://pantheon.io/docs/articles/organizations/vanity-domains/) page we say:
> the ability to replace the default Platform domain (pantheonsite.io) with a custom Vanity domain for each environment on every site running on the platform.

Now the behavior is Vanity domains are provisioned in *addition* to default Platform domains. All environments get a Platform domain.

**Comment by bmackinney** [comment]
@pantheon-systems/documentation these are our platform changes for the month so far. Let us know whether we missed something ASAP:

**Freezing Unused Sites**    
Sites in an Organization that have not been accessed in <time period> are now frozen due to inactivity. But don’t worry--you can click **Unfreeze Site** on your Dashboard if you still need it.
**Docs Site Changes**  
We updated the Docs landing page to show the five top docs in each category, added a Featured category to give you quick access to the most frequently used docs, and simplified the URLs. [Check it out](https://pantheon.io/docs/)!
**Terminus 0.11.0 Released**
If you haven't updated in a while, check out the [Terminus Changelog](https://github.com/pantheon-systems/cli/blob/master/CHANGELOG.md) and get the [latest version](https://github.com/pantheon-systems/cli/releases).

@slivermon should we take out or leave in Freezering?
