### ISSUE TITLE
New Doc: Alternate Docroot

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/documentation#1651]
## Title
Alternate Docroot

## Description
Register an web docroot one level below the git/code root.

## Outline
- Create a `pantheon.yml` file in the git/code root
- Add `web_docroot: true` to `pantheon.yml`
- Create the `web` sub directory in the git/code root
- Migrate the sites code files to the newly created `web` directory

## Purpose
Keep non-web files, such as local `.env` files and Quicksilver scripts, outside of the docroot. Allow Pantheon to be friendlier for Composer based workflows.

## Expected Audience
Power Users/Developers

## Path
`source/_docs/alternate-docroot.md`

cc @greg-1-anderson

**Comment by dustinleblanc** [comment]
Is this fully supported now? @ataylorme @greg-1-anderson @stevector

**Comment by greg-1-anderson** [comment]
I use the following to relocate my files:

Drupal 7:

`mkdir -p web && git mv $(find . -type f -maxdepth 1 | grep -v pantheon.yml) includes/ misc/ modules/ profiles/ scripts/ sites/ themes/ web
`
Drupal 8:

`mkdir web && git mv $(find . -type f -maxdepth 1 | grep -v pantheon.yml) core drush modules profiles sites themes vendor web`

The idea here is that `find . -type f -maxdepth` finds all files at the document root, including the "dot" files, but skips all of the directories. I list the directories in Drupal core out specifically, so that any user-defined directories stay behind.  This may or may not produce the correct results, depending on what files the user has added.

**Comment by greg-1-anderson** [comment]
@dustinleblanc: Moving in that direction.

**Comment by ataylorme** [comment]
Added an initial doc in [PR 1652](https://github.com/pantheon-systems/documentation/pull/1652). About to hop on a plane but I'll hopefully have time to update next week.

Any comments and changes are most welcome.

**Comment by mikeschinkel** [comment]
Hate to look a gift horse in the mouth (been asking for this for 1+ years... :-)  but any chance we can configure the name of the docroot?   Our [WPLib Box](https://github.com/wplib/wplib-box) for WordPress has standardized on `/www` for the web root and it would be great if we could support Pantheon directly without a build step.

**Comment by spesic** [comment]
Yes, pretty please! :D

@mikeschinkel as long as nginx is configured to follow symlinks you should be able to solve this by simply creating a symlink web that points to www.

**Comment by greg-1-anderson** [comment]
Configuring the name of the web root is not supported, but creating symlinks from your desired document root to 'web' works.

**Comment by mikeschinkel** [comment]
@spesic Thanks. However I don't think a symlink will address the reason for my request, but if it will please let me know, I am open to understanding.  

The reason we want to configure the web root file name on Pantheon is so that when our commit to their Git repo on their Pantheon account it will work correctly. But I don't think they can symlink `web` on our local machine and commit that and have transfer the symlink Pantheon, or can it?

@greg-1-anderson Thanks for the reply but I am confused. As far as I know Pantheon does not provide `ssh` access, right?, so how would I one of our users symlink if they cannot`ssh` into your servers?

**Comment by ari-gold** [comment]
@mikeschinkel Yes, you can create a symlink locally and push it up. Related doc: https://pantheon.io/docs/non-standard-file-paths/

**Comment by mikeschinkel** [comment]
@ari-gold Oh, excellent!  Thank you.

**Comment by albertski** [comment]
If we use a custom upstream (or even Pantheon's upstream), will it know to update core inside the web directory? Or should we update the upstream to have core inside the web directory?

**Comment by Luukyb** [comment]
Great! This worked on a fresh d7 project.
Move everything to a new folder "web" using @greg-1-anderson command. Then add a new file pantheon.yml with two lines: "api_version: 1" (this is required) and "web_docroot: true", and it worked.
Thanks!

**Comment by ataylorme** [comment]
@greg-1-anderson here is the move command updated for WordPress:

`mkdir web && git mv -k $(find . -type f -maxdepth 1  | grep -v pantheon.yml) wp-includes wp-content wp-admin web`

I would add the `-k` option to [`git mv`](https://git-scm.com/docs/git-mv) for your Drupal commands as well. It allows the move to take place even if there are files `find` captures that are in `.gitignore`. In my case it was a Terminus `.env` file, which I purposefully ignored.

**Comment by mikeschinkel** [comment]
Is there a documentation page for this new feature somewhere?

**Comment by rachelwhitton** [comment]
@mikeschinkel: [Serving Sites from an Alternate Docroot](https://pantheon.io/docs/alternate-docroot/)

**Comment by rachelwhitton** [comment]
@mikeschinkel: [Serving Sites from an Alternate Docroot (Beta)](http://beta-static-docs.pantheonsite.io/docs/alternate-docroot/)

**Comment by derimagia** [comment]
Found an issue with this where you can commit the/in the sites/default/files directory with this on a multi-dev. (Was directed to post it here by support when submitting the issue)

Repo steps:
1) Make new repo
2) Create new multidev and switch to it
3) Add new pantheon.yml file with new web root option. Add all files to the web root. (You can follow the instructions in the docs for this). Remove the .gitignore file as well (or remove the sites/default/files from it) and commit and push up
4) Add a file to web/sites/default/files/test.txt and commit and push up. This throws an error on the master branch but not a multidev. Once this is done you can merge it into master and then it's not easy to fix unless you use the bug again

Let me know if you need any more info - this gave us a little bit of a hassle

**Comment by ataylorme** [comment]
@greg-1-anderson - see above. I'm out of the office until Tuesday but will try to reproduce when I get back in.

**Comment by ari-gold** [comment]
@derimagia  Thanks for bringing this to our attention. Yes, the nested web docroot is not yet officially supported (but will be soon!). We've created a BUGS card, will investigate, and report back.
