### ISSUE TITLE
Search Result Font Size

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#1674]
Re: [Search Results](https://pantheon.io/docs/search/?term=updates)
## Issue Description
Reported in slack by @ccorpus : 
>It looks smaller and more difficult to read.

Other pages seem fine, issue pertains to search results styling only. 
## Suggested Resolution
Up the font size and override Google stylesheet for result titles (`.gs-result .gs-title, .gs-result .gs-title *`)

**Comment by rachelwhitton** [comment]
@kimby77 @informanddelight thoughts?

**Comment by kimby77** [comment]
The font also seems to be wrong - it is using Arial (13px) instead of the Avenir font used across the public site.  I'm wondering if the search results are pulling in an external stylesheet, or if something broke here?

It looks like the font defaults for the public site is Avenir at 16px so we should use that here for consistency.
