### ISSUE TITLE
Load and Performance Testing Doc Update

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/documentation#1851]
Re: [Load and Performance Testing](https://pantheon.io/docs/load-and-performance-testing)
## Issue Description:

Title of doc is Load and Performance Testing, but doc intro is all about Load testing, so let’s revise it!

We should talk about 
1. **Load** vs **performance** testing, highlight value of smooth scaling and consistent infrastructure. Performance characteristics of Live are same as other environments so if it’s slow on Dev, don’t deploy Live. If you uncover performance issues with a single request, no need to conduct a load test, fix the performance issue first!
2. How to do performance testing in Dev/Test. Highlight New Relic
3. Load testing in Live environment **before launch**
4. Use math to calculate load capacity **after launch**. After launch, you can establish a baseline that X response time will let you handle Y traffic. If X degrades in Dev/Test, that will impact how much traffic Live can handle. We do not recommend load testing in Live after launch because you risk overwhelming your Live site and causing downtime. 

Add heading:
How to calculate how much traffic you can handle:

If you know traffic will increase,  you can understand the relationship between your site’s performance and how much load it can handle by doing a little math.

Maybe best way to communicate above is via a table, like this interactive spreadsheet? (https://docs.google.com/a/getpantheon.com/spreadsheets/d/1K9BdmdJDqHMvHMaerZZmCcflSvmEJhgBsGL8zwjpxE8/edit?usp=sharing)

For example, if your application's average response time is Xms and the Live environment gets Y requests per minute (rpm), then a Business plan with 16 php workers will handle the load. If you anticipate a traffic increase and you’d like to upgrade to Elite, then <contact Sales>.   (validate this math based on new pricing comparison doc)

Note that
Dev environments defaults to not cache static assets like CSS and JS to facilitate development. This will affect frontend performance of those environments, and you should be aware of that if you are perf testing there.

Also include link to https://pantheon.io/docs/guides/load-testing-with-blazemeter

**Comment by rachelwhitton** [comment]
Include content for analyzing CPU usage in New Relic (originally reported in #2022)

A client is running a load testing using loadrunner and they are too concerned about the cpu utilization when running the test.

"We are using HP LoadRunner, 10 concurrent users for 25 min doing Login, navigate through 2 pages and Logout. Total transactions for each step is 3,400 throughout the test." - From Client

From New Relic it captures 118% cpu utilization and this why client is too concerned of this result, but as per @ari-gold theres nothing to be concerned with because the platform is on a multicore cpu.

See https://pantheon-systems.desk.com/agent/case/77635
