### ISSUE TITLE
Export an Existing WordPress Site Doc Update

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#1998]
Re: [Export an Existing WordPress Site](https://pantheon.io/docs/wordpress-export)
## Issue Description:

The following section no longer works. No more option to import a site from archive files. The new migration tool now uses Pantheon Migration plugin.

> Prepare Your Archive for Import
You now have three individual files that make one complete archive of your WordPress site. The import screen allows you to toggle between uploading your archive files or supplying a remote URL (e.g. Amazon S3, Dropbox, your existing server, etc.) to fetch the archives.

>You can upload each of your archive files separately, or package the archives within a single file. The max file upload import size is 100MB total. URL imports are limited to 500MB per input.

> Note: Modify Dropbox URLs to end in dl=1 instead of the default dl=0. This forces a download of your archive and avoids the Dropbox landing page.

## Suggested Resolution 

Remove this section.

**Comment by alexfornuto** [comment]
@rubelyn I took your suggestions and expanded upon them. Since this guide seems to be mostly geared towards an import method that no longer exists, I refactored it to apply better for situations where you would still want to create archives. Please take a look at #2444 and let me know what you think.
