### ISSUE TITLE
New Doc: Drupal 8 with Commerce

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2139]
Re: Chat ID#7713272932
> I attempted to install and uninstalled so many times that I ended up creating a file with instructions for myself.

**Test, validate, and document the following:**
Installing Drupal Commerce 2.x on Pantheon

0. Make sure your PHP version is compatible with Pantheon

1. Install git, if necessary

2. Install composer, if necessary

3. Create a new site on Pantheon, note site name, deploy Drupal 8, DO NOT INSTALL

4. Put site in git mode

5. Copy your Git Connection Info into a text file to get the ssh:// ... repository.git URL

6. In terminal, navigate to location for local site root

7. Execute commands, replacing my-site with your site name and ssh://ID@ID.drush.in:2222/~/repository.git with your repository URL:

$ composer create-project pantheon-systems/example-drops-8-composer my-site

$ cd my-site

$ composer prepare-for-pantheon

$ git init

$ git add -A .

$ git commit -m "web and vendor directory from composer install"

$ git remote add origin ssh://ID@ID.drush.in:2222/~/repository.git

$ git push --force origin master

<see: https://github.com/pantheon-systems/example-drops-8-composer>

8. Return to Pantheon site, switch to SFTP more

9. Visit Development Site, install, select Standard profile

10. Switch site back to git mode

11. Execute these composer commands to install Drupal Commerce:

$ composer config repositories.drupal composer https://packages.drupal.org/8

$ composer require "drupal/commerce 2.x-dev"

<see: http://docs.drupalcommerce.org/v2/getting-started/install.html>

12. Use the composer prepare-for-pantheon command again to get rid of submodule repositories:

$ composer prepare-for-pantheon

13. Commit and push changes to Pantheon

$ git status

$ git add -A .

$ git commit -m "Install Drupal Commerce"

$ git push origin master

14. Return to Pantheon and install Commerce modules: Product, Checkout, Cart

**Comment by paul94010** [comment]
Thanks so much for posting this.  I have been struggling with this install for the last three days.   Now I understand why I am struggling.   If the Commerce Guys intend their system to be adopted widely, they clearly need to improve the install process.

**Comment by paul94010** [comment]
Rachel, I can't get your instructions to work for me.   The problem seems to be that the links in your post are no longer valid.   (I get 404 errors on them.)
Also, this command line:

$  composer require "drupal/commerce 2.x-dev"

results in the following error message from Composer:

 - The requested package drupal/commerce could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting

Do you have any updates?

**Comment by zengenuity** [comment]
These instructions are really helpful, but unfortunately they currently don't work, because the latest Commerce dev requires Drupal 8.3.x, and the example-drops repo only has 8.2.6. So, you'll get stuck at step 11.

Another issue at step 11: The composer.json in example-drops repo has minimum-stability set to alpha, so you can't install the dev version of Commerce. Even if you try to ```composer install drupal/commerce```, it fails because the beta6 version of Commerce requires dev versions of Profile and Address modules. When I tried switching minimum-stability to dev, that's when I ran into the issue of needing 8.3.x.

**Comment by 2ndMile** [comment]
example-drops repo has now been updated to 8.3.2 so these directions work once again. Thank you!

**Comment by Bowevil** [comment]
@rachelwhitton thank you so much for the answer! I have been doing the same install/uninstall for two days. What a royal pain to go through, but worth the effort.

**Comment by alexfornuto** [comment]
@Bowevil https://www.youtube.com/watch?v=6uBmii5es7Q

**Comment by alexfornuto** [comment]
For anyone who's been following this issue, the new doc based off of these instructions is now ready for review: #2919

**Comment by alexfornuto** [comment]
Forget #2919, that's old news! The currently drafted guide is being reviewed at #3014
