### ISSUE TITLE
Serving Sites from the Web Subdirectory Doc Update

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#2267]
Re: [Serving Sites from the Web Subdirectory](https://pantheon.io/docs/nested-docroot)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
It is not clear on how to update the core manually. 

This works for me:
`git pull -Xtheirs git://github.com/pantheon-systems/drops-7.git master`

Updating the core via Drush is not allowed. Seeing the following:

`Do not update via Drush. See:https://pantheon.io/docs/articles/sites/code/applying-upstream-updates/ (SECURITY UPDATE available) `

## Suggested Resolution 

- Add steps on how to manually update the core or add a link on how to pull from our upstream -https://pantheon.io/docs/upstream-updates/#resolve-conflicts-locally.

**Comment by rachelwhitton** [comment]
+1 @stevector @greg-1-anderson do you have any recommendations for how users should apply core updates for sites served from a subdir? Would be the same as what's recommended here: https://pantheon.io/docs/upstream-updates/#resolve-conflicts-locally

**Comment by stevector** [comment]
Hmm, I would have guessed drush or wp-cli as the default answer. I think the guidance above is true when the web docroot is not relocated and we specifically want people to use dashboard one-click updater.

**Comment by stevector** [comment]
We could also mention that the web docroot is something often chosen when using Composer to control core. Then the core updates should be coming from Composer commands.

**Comment by greg-1-anderson** [comment]
While you **can** use Composer on a site that does not have a relocated document root, doing so presents numerous problems and complications. It is therefore recommended to always use `web_docroot: true` in your pantheon.yml for any site that uses Composer.

While you **could** update a site with `web_docroot: true` via some technique other than Composer, doing so will usually be sub-optimal in most use-cases. In order to use Pantheon's upstream-updates process with a site that has a relocated document root, you would need to manage the core updates in a custom upstream, as Pantheon does not maintain any upstreams with relocated document roots ourselves.

Thus, at the moment our recommendation for Composer-managed sites : relocated document root sites is 1 : 1. If you do one, then you should do the other.

In the future, we may support upstreams with a relocated document root, or running Composer update from the dashboard. Until then, users should either use `terminus composer update` or the [Terminus Build Tools workflow](https://github.com/pantheon-systems/terminus-build-tools-plugin) to manage their relocated-documentroot sites.

I will support a documentation page for the later at some point, but haven't written it up yet.

**Comment by stevector** [comment]
I think the open question is "how should sites that have relocated the docroot (but don't use Composer) update Core?"

**Comment by greg-1-anderson** [comment]
That question doesn't have a convenient answer. If indirect composer use is allowed, then you could use Composer to manage a private upstream, and the Dashboard to update all of your sites.

You could try to use Drush to update your site, but that isn't really supported at the moment, and Drush is moving away from supporting the `pm-*` commands.

If the site is WordPress, then you can update it with wp-cli.

However, I think in general I'd stand by recommending Composer for updating Drupal sites with a relocated document root, and simply not supporting updating without Composer. If that's not a good answer, then I think that Pantheon should start maintaining an upstream with a relocated document root.

**Comment by greg-1-anderson** [comment]
I suppose the best "roll your own without Composer" answer would be to use a git subtree to manage the upgrades, but I think that might be a bit complicated for users who find Composer complicated.

**Comment by stevector** [comment]
So to summarize:

<table>

  <tr>
<td colspan="2" rowspan="2"></td>    
<td colspan="2">web_docroot</td>
  </tr>
  <tr>
    <td><b>Yes</b></td>
    <td><b>No</b></td>
  </tr>

  <tr>
    <td rowspan="2">Uses <br>Composer to control <b>core</b></td>    
    <td><b>Yes</b></td>
    <td><a href="https://github.com/pantheon-systems/example-drops-8-composer">We have an example in-progress</a></td>
    <td>Probably a bad idea that we should discourage.</td>
  </tr>
  <tr>
    <td><b>No</b></td>
    <td>You can update WordPress this way with WP-CLI. For Drupal we should recommend only using web_docroot with Composer (or provide an upstream)</td>
    <td>Normal dashboard workflow</td>
  </tr>
</table>

Greg, it's not clear to me why using Drush to update core on the case of web_docroot yes / Composer no is not viable. Even if Drush will eventually remove that command, the command is there now, yes?

**Comment by alexfornuto** [comment]
There's a note in place suggesting the current best practice for updating core with nested docroot:

>One-click Dashboard updates are only compatible with the nested web docroot feature when the web_docroot property is set in the pantheon.upstream.yml file of the upstream. We recommend using a Custom Upstream if you would like to continue to utilize Dashboard updates.

This is the best choice currently, but this guide should be reviewed after larger D8+Composer+Pantheon issues are sorted.
