### ISSUE TITLE
Backup scripting.

### ISSUE THREAD

**Issue by alexfornuto** [pantheon-systems/documentation#2306]
Re: https://pantheon.io/docs/backups/
## Issue Description
Backup code sample treats $BACKUPDIR as a file, not a directory. 
## Suggested Resolution
Correct example script.

**Comment by alexfornuto** [comment]
@ttrowell you recently tested out S3 access, did you run the backup script sample?

**Comment by ttrowell** [comment]
So, this is presenting a few unexpected issues.  The <--to>  parameter in the Terminus command is actually wanting a file _name_ and not just a folder on the local, so it seems to need to be defined. That causes a problem since the name is the same for each backup you want to create (code, database, files) so I'm working in that.

The remote upload ended up being the link to the backup and not the backup itself - so that was also unexpected.  Still debugging...
