### ISSUE TITLE
Can sites using Free HTTPS Service also use CloudFlare?

### ISSUE THREAD

**Issue by lauren-kelly** [pantheon-systems/documentation#2460]
Re: https://pantheon.io/docs/free-https/
## Issue Description
With the addition of Free HTTPS some users have questions about how to configure the site with Cloudflare

## Suggested Resolution
add in CloudFlare config information

**Comment by ari-gold** [comment]
Yes, you can continue to use Cloudflare. Unless you require a special feature from Cloudflare (e.g. WAF) then we recommend using Cloudflare for DNS-only. To do so, from Cloudflare DNS settings, click the orange cloud so it greys out. You can also keep using Cloudflare as a CDN on top of the Pantheon CDN, in which case the Pantheon Domains tool will show action required because the DNS detected will be Cloudflare IP addresses and not match our recommendations. As long as your DNS is no longer routing to a legacy loadbalancer, you can safely ignore the action required warning.
