### ISSUE TITLE
Automated Testing for WordPress with Behat Doc Update 

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/documentation#2469]
Re: [Automated Testing for WordPress with Behat](https://pantheon.io/docs/guides/wordpress-automated-testing/)

Priority (Low):

## Issue Description:
A customer has had trouble following the guide with setting up tests.
See Case 84095

## Suggested Resolution 
Review and test to ensure accuracy.

**Comment by ttrowell** [comment]
@ari-gold If this doc has already been recently created or reviewed, please note it here.  Thanks!

**Comment by sagarsarkar** [comment]
Is there any solution?

**Comment by alexfornuto** [comment]
I've reached out to @stevector who's working on a suite of Behat tests for our WordPress upstream, and will help update or rewrite this guide once it's complete.

**Comment by ataylorme** [comment]
We've switched to using [WordHat](https://github.com/paulgibbs/behat-wordpress-extension/) for Behat testing in our newly created [WordPress Composer Example Repo](https://github.com/pantheon-systems/example-wordpress-composer).

I would love to see us help improve the WordHat documentation directly and refer folks to our example project and those docs rather than duplicating work.

**Comment by rachelwhitton** [comment]
+1 @ataylorme 

I think it's best to retire this guide in favor of the build tools guide (which will soon feature WP example per #2665 - in progress now). 

This issue should be closed by a PR deprecating the Behat guide since we are no longer committed to maintaining it. We've discussed using a deprecation banner so we can leave the page up and accept public contributions -- @alexfornuto have you made any decisions on that in the style guide or not yet? thoughts?
