### ISSUE TITLE
New Doc Proposal: Migrate Local Sites

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#2741]
Priority (Low‚ Medium‚ High): Medium

## Title
Migrate Local Sites to Pantheon 

## Issue Description
Some users end up on the more difficult manual migration path when moving a local Drupal site to Pantheon because step 3 of the guided migration path assumes the site is already live somewhere else. 

## Outline
Intro that summarizes guided migration path is best when migrating a local site
Cover exceptions that may require manual migration
Recommend WP users install the plugin on their local site
Provide steps to move a local Drupal site that do not require a custom domain
Troubleshooting

## Expected Audience
D7 and D8 users looking to take a local site live on Pantheon

## Path
`/docs/migrate-local`

## Next Steps
- [ ] Get @pantheon-systems/cse input based on support trends such as common issues/questions, terminology (migrate vs import vs upload?)
- [ ] Strategize doc update with a corresponding dashboard update so step 3 in the guided path links to new doc

**Comment by kimby77** [comment]
+1 on this idea!

* What information do we have available that can inform this content? (Use cases discovered, tickets received, other things?)
* Are there any existing docs we have that we should be aware of when considering this one?

**Comment by eabquina** [comment]
This is a great idea! It would be great to consolidate the tools for exporting local site. My favorite docs page is the Drush Import method. It's great because it asks to upload the archive to a web location and run via terminus. 

https://pantheon.io/docs/drush-import/

There are also use cases where they use tools like Kalabox, DevDesktop or plain old MAMP/XAMPP
https://pantheon.io/docs/kalabox/ (how to create in Kalabox then upload) 

For WordPress,  I just use All-in-One Import tool, which is kind of like the drush ard method.
This generated a .wpress file that you can import to a new site, but requires you to have a fresh install first and just overwrite content once uploaded. 

https://wordpress.org/plugins/all-in-one-wp-migration/

I wonder if this can be done via WordPress too via terminus import:site? Will try to test if placing any URL will do as long as the archive is there.

**Comment by alexfornuto** [comment]
After discussion, we're going to expand [this section](https://pantheon.io/docs/migrate/#how-do-i-migrate-a-local-site-to-pantheon) of the existing migration doc.
