### ISSUE TITLE
WooCommerce Docs

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2816]
Re: [WordPress Known Issues](https://pantheon.io/docs/wordpress-known-issues/)

Priority (Medium):

## Issue Description:
WooCommerce is an important WordPress plugin that enables the biggest of sites. Having a good docs page about it would help a lot of folks, and also ensure us we track support and entice more WooCommerce sites to migrate to Pantheon

We also would list common issues like:
- WooCommerce errors and additional plugins
- trying to batch upload xxxx number of products, which uses a script that usually timeout
- Optimizing for performance, caching and other best practice (blog/optimizing-woocommerce-pantheon-advanced-page-cache-wordpress)

## Suggested Resolution 
To create a /docs/woocommerce page for WooCommerce best practice.
Link and relate from docs/wordpress-known-issues/
Consolidate and merge all woocommerce blog and tips so far

**Comment by alexfornuto** [comment]
@eabquina Are there any specific concerns or 'gotchas' when installing WooCommerce on our platform versus any other? Do they have documentation that covers the concerns you want to address?

**Comment by eabquina** [comment]
@alexfornuto i wrote this issue because i had consecutive chats / ticket where they were trying to "batch upload" products (around 700-1500 items). Woocommerce script timeout due to the platform limit of 120 seconds (php runtime) for scripts.

We had to tell them that the best way to do this is to clone their site, Import the woocommerce items locally, and then sync the database (which now contain the new items) up to the server. This guide could be one troubleshooting entry for this new docs we'd make.

So here, we may discover more like this on the platform when specific to woocommerce. 

And also, would like a page that would cover the good stuff like performance and caching etc.

**Comment by rachelwhitton** [comment]
Sounds like handling batch uploads is the only problem the docs (and cse) _need_ to support, since it requires a workaround specific to handling content & data across multiple environments. But I'd rather not own performance tips or usage recommendations - too hard to manage over time.

**One possible solution..**
Let's add woocommerce to the known issues doc with workaround and a link to [the related blog post](https://pantheon.io/blog/optimizing-woocommerce-pantheon-advanced-page-cache-wordpress) for more tips on how to optimize usage 

**Another possible solution..**
If we don't want this plugin on our unsupported doc page.. an alternative solution would be to make a generic statement in platform considerations doc re: timeouts on batch uploads and a general process for handling the upload locally then import via the site dashboard (safely, of course)  Send folks in chat/ticket a link to [the related blog post](https://pantheon.io/blog/optimizing-woocommerce-pantheon-advanced-page-cache-wordpress) for tips on woocommerce as it comes up


Either way, my preference is to reduce the scope of this issue.
