### ISSUE TITLE
Undo Git Commits vs LIVE code backup + SFTP

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2833]
Re: [Undo Git Commits](https://pantheon.io/docs/undo-commits/)

Priority (Low):

## Issue Description:
User is not comfortable using Git / Terminus and asks if the alternative of downloading LIVE code from backup would work well

## Suggested Resolution 
Check and review possible issues if done using SFTP + LIVE backup and not using Git
Say if this is not really allowed or advisable, and possible impact

**Comment by alexfornuto** [comment]
> Say if this is not really allowed or advisable, and possible impact

It's not advisable, because it's easy to mistakenly override incorrect file paths when manually copying and uploading from a backup archive via SFTP.

The place to discuss this is probably [here](https://pantheon.io/docs/restore-environment-backup/#restore-an-environment-from-another-environments-backup)

**Comment by alexfornuto** [comment]
@eabquina what was the user trying to accomplish with the backup from Live? If they wanted to override their Dev environment from live, that could be done directly from the Site Dashboard.
