### ISSUE TITLE
Flush Cache of Redis via CI (Quicksilver)

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2898]
Re: [Installing Redis on Drupal](https://pantheon.io/docs/drupal-redis/)
[Quicksilver](https://pantheon.io/docs/quicksilver/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Redis Flush needed for automated build care of Customer, especially for cases of new modules or features for sites

## Suggested Resolution 
As workaround, we can trigger enable and disable Redis via terminus, 

```redis:disable <site>```
```redis:enable <site>```

If this is preferred, can be placed in both docs. 

If there is a way on how to get the Redis Env Variables also so can be done via a webscript;
https://pantheon.io/docs/read-environment-config/

**Comment by alexfornuto** [comment]
Reached out to @eabquina for clarification.

**Comment by rachelwhitton** [comment]
I wonder if it's better to update our example repos to do this on redis enabled sites? If this needs to be done on each build, it should probably be baked into the repos so folks don't have to debug or search docs for the fix

**Comment by dustinleblanc** [comment]
Disable/enable Redis is definitely not the right way to go, There should be a PHP function available to flush Redis, I believe Drupal's `cache_clear_all` should work. I'll test that out to be sure

**Comment by stevector** [comment]
@rachelwhitton I don't want to add Redis modules/plugins to `example-drops-8-composer` and `example-wordpress-composer` because Redis is not available at the Personal plan level. I'd be fine with documenting instructions in `settings.php` and `wp-config.php`.

Though FWIW, I don't understand exactly what this issue is asking @eabquina. I think the suggestion here is to add documentation for how to clear Redis specifically as part of a CI process, yes? I would think that an site that needed Redis cleared as part of build/deployment should be doing a full cache clear at the Pantheon level with `terminus env:clear-cache` or at the CMS level with something like `drush cr`.

**Comment by dustinleblanc** [comment]
I think an existing bug will make `terminus env:clear-cache` fail unpredictable

**Comment by eabquina** [comment]
@stevector "...think the suggestion here is to add documentation for how to clear Redis specifically as part of a CI process, yes? "  Yes! The context was having new/delete/update modules for the site. The site would have errors, and then running a Redis flush fixes it. What should be the correct way to do it? 

Unfortunately clearing the cache did not clear Redis cache (both via dashboard and terminus). We both tried on the spot. After that, it was the customer who tried disable/enable, and then it worked. 

In the Redis docs, it has to be via the command line, logged into the Redis server. But unsure if this can be translated as part of CI process.
https://pantheon.io/docs/drupal-redis/#clear-cache

**Comment by stevector** [comment]
A CI process could do something like `$(terminus connection:info composer-redis-debug.dev  --field="redis_command") flushall` but I think we're better off putting energy into solving BUGS-633 so that an extra step isn't necessary.
