### ISSUE TITLE
WordPress Licenses for multi-environment use

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#2946]
Re: <New Doc>

## Issue Description
Users ask recommendation about what to do for plugins that have licenses.

## Suggested Resolution
Personal suggestion is to link in DEV to update, and then link the license in LIVE manually
Any other suggestion is welcome.

**Comment by alexfornuto** [comment]
@eabquina this issue is incomplete. What doc would we edit? Would instructions be universal for all licensed plugins, or specific based on the type of license? Have other @pantheon-systems/cse's or @pantheon-systems/cse-admins provided any input on best practices?

In short, is there a general answer here we can document, or are solutions going to be specific to the customer and/or plugin?

**Comment by eabquina** [comment]
@alexfornuto modified the issue now. I think this is fit for the unsupported plugins doc as a section to comment in general about plugins that have licenses. Key points for me to include are:

- Highlight that plugins with licenses are allowed in Pantheon, but consider constraints for as for its terms, in relation to Multi-dev use
- Licensing issues are for Customers to Resolve, as per the terms of their plugin or themes
- Customer has to manually assign, re-assign licenses in cases plugins don't work etc per environment

In the future, there may be a plugin specifically has an issue that is caused by license structure. Would make a separate plugin Issue/Solution entry here.

**Comment by alexfornuto** [comment]
@eabquina sounds good.

**Comment by rachelwhitton** [comment]
Suggest new doc for this content, cross link as appropriate.

**Comment by alexfornuto** [comment]
After reviewing with @rachelwhitton we're calling this issue closed by #2983. If we discover a more generalized set of instructions we can give that will apply to "most" paid plugin issues, we can reopen.
