### ISSUE TITLE
Switching Sites from HTTP to HTTPS Doc Update 

### ISSUE THREAD

**Issue by stephencross** [pantheon-systems/documentation#3037]
Re: [Switching Sites from HTTP to HTTPS](https://pantheon.io/docs/http-to-https/)

Priority (Low‚ Medium‚ High):  Medium

## Issue Description:

The section describing how to the change your settings.php to force https breaks local development.  I'm using Lando and it forces the url to https, which does not work. 

## Suggested Resolution

**Comment by dustinleblanc** [comment]
Hi @stephencross. Lando provides a certificate that is self-signed for running local development. While you are presented with a cert warning, you can just accept the warning and continue developing. Since this is running on your local system and you are the one 'running the site' you don't need to worry about the cert error. The Lando folks may eventually fix this so it auto-trusts to certs (Like Laravel Valet does), but until that time, it's just a matter of a untrusted certificate.
