### ISSUE TITLE
New Relic APM Infrastructure Monitoring

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3064]
Re: [New Relic APM Pro](https://pantheon.io/docs/new-relic/)

Priority (Low):

## Issue Description:
The customer is asking if it is possible to get bandwidth, network or other monitoring tools related to INFRASTRUCTURE or SERVER module of New Relic. 

A couple of customers want to calculate how much "Mb or Gb" does their website consume. Some customers would use this for getting External CDN where Bandwidth usage is monitored.

## Suggested Resolution 

Currently, Infrastructure and Server monitoring modules of New Relic is disabled. In the docs, it would be good to have verification that this is not possible (due to some platform constraint) and provide some alternatives. Cite references on why this is not possible and the lead to alternatives.

Also, provide comments about cases where we cannot fully measure bandwidth usage because traffic are served by Edge Cache or Global CDN.

**Comment by rachelwhitton** [comment]
@eabquina Rejecting this issue for now. We can re-open once discovery work has been done to identify action items. 

I'm not sure I understand the issue described, but more importantly the resolution needs to be one we can act on.

**Comment by eabquina** [comment]
@rachelwhitton I've modified the description hoping to make it more clear this time :)

Several customers are trying to get a way to measure bandwidth usage. Supposedly, New Relic has this feature, but it seems to be disabled. 

I can recall 3 instances where I handled this for a customer. A specific scenario was for trying to choose a plan for StackPath. Plans start at 200GB for "Included Global Bandwidth / month" limit. Because they don't have history or data about bandwidth usage from Pantheon, they are unsure how to move forward.  

Can we say in the docs that this is simply not possible or should we point alternatives on how they can measure outside New Relic.

**Comment by rachelwhitton** [comment]
Thanks for the details @eabquina! +1

**Comment by tinefin** [comment]
Sharing my motivation for why I am not creating a feature request:
- I think the question is coming up as customers need custom certificates and choose StackPath which is the cheapest. They bill on bandwidth:
https://www.stackpath.com/pricing/
My humble guess is that far the most customers will fit into the cheapest plan.
- In order to find out bandwidth, you can sign up for a month (20$), see how much bandwidth is use and change plan accordingly next month if need be.
- Logging / measuring bandwidth adds delay to every request
- In the first place, they don't actually get a higher level of security with their custom EV certs. (David S has more info here, that might be relevant for the custom cert doc).
- I can't see any other reason why we need to know monthly bandwith usage pr site.

### New Relic
Also, measuring mb has nothing to do with New Relic. This is a common misconception that comes up a lot, also in connection with OOM errors.
New Relic measures processing time, not mb's (!).

Even if we had the full New Relic server monitoring in place, my experience with New Relic so far has been that it can't measure correctly for VMs. I would guess this is worse for containers.

And then.. New Relic only knows about the requests served from appserver (uncached traffic). Cached requests are served from Varnish.

**Comment by eabquina** [comment]
@rachelwhitton @tinefin   seeing the new Docs about Preventing Plan Abuse, it says "To prevent plan abuse, we measure requests served by the platform from the CMS."  I wonder if this is data that can be asked now by a customer?

**Comment by rachelwhitton** [comment]
@eabquina that sounds like a separate "thing". This issue is asking for bandwidth data for a site to help them determine plan level on some external service, like StackPath. I don't think our measuring page views relates to the bandwidth question (at least in this context). 

I think the resolution to this issue is a quick FAQ somewhere stating that we do not provide bandwidth usage insights.

**Comment by rachelwhitton** [comment]
After talking with @tinefin, I can see how it makes sense for users to jump from "can i see bandwidth?" to "how many pageviews?" but I do think these are separate questions so I made another issue to address pageviews. 

**The resolution for this issue should be a section added to the new relic doc explaining that we do not provide bandwidth insights.**

Refer to issue #3091 for updates on if/when/how we expose pageviews for similar reasons.

**Comment by tinefin** [comment]
I think it would be awesome to add this somewhere - but I am not sure the New Relic doc is the right home for it.
New Relic APM has nothing to do with bandwidth, mb's or even page views for that matter.

- I should really write a section on that doc about what New Relic can and cannot be used for =)

**Comment by alexfornuto** [comment]
Now that we have the [Pageview Limits and Overages](https://pantheon.io/docs/pageview-limits/) doc, should we address this information there?

**Comment by eabquina** [comment]
@alexfornuto I agree. Best to put there the "how many pageviews" or how it was counted etc.

**Comment by alexfornuto** [comment]
Closing in favor of #3091
