### ISSUE TITLE
New Relic APM Pro Doc Update 

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/documentation#3110]
Re: [New Relic APM Pro](https://pantheon.io/docs/new-relic/)

Priority (Low‚ Medium‚ High):

## Issue Description:
Add a section on how New Relic account upgrades work. For instance, if customer wants to purchase Browser Pro as well (Pantheon supplies APM pro).

There is a particular email for that:
pantheon@newrelic.com

More info here:
https://pantheon.io/blog/pantheon-new-relic-more-what-you-get

- Might be good to double check with Pantheon New Relic team if this is indeed still the process.

## Suggested Resolution

**Comment by alexfornuto** [comment]
@tinefin: @rachelwhitton and I have discussed a possible **Suggested Resolution**. Because, at this time, the only way to add additional NR services is through our Sales Team, we're considering clarifying the FAQ section on "How much is new relic?" to say so. (We'll also make the FAQ sections anchored and linkable.)

Does this sound like an appropriate resolution to you?
