### ISSUE TITLE
Warn about problems migrating WPEngine sites

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/documentation#3441]
Re: [Launch Essentials](https://pantheon.io/docs/guides/launch/domains/)

Priority (Low‚ Medium‚ High): Med
## Issue Description:
We're getting a lot of WPEngine customers who are migrating over and dealing with the fact that WPEngine blocks them placing the challenge file on their old site (because WPEngine redirects the request to their own cert provisioning service). We may want to explicitly call that out in docs (and the dashboard maybe?) so that folks don't get a nasty surprise at launch

**Comment by rachelwhitton** [comment]
@dustin, thanks for the issue! The path they'd follow now is documented in the "Maintenance Window" subsection of "Existing Sites". It may be best to call out WPE specifically, but I'd want that done with some product oversight. My preference would be to close/reject this but could be convinced otherwise. 

@ari-gold can you weigh in? 

Moving to "consider" for now until product weighs in

**Comment by alexfornuto** [comment]
[This](https://pantheon.io/docs/migrate/#how-can-i-migrate-from-wp-engine) is another possible location for the requested information.
