### ISSUE TITLE
Role-Based Permissions & Change Management Doc Update 

### ISSUE THREAD

**Issue by rubelyn** [pantheon-systems/documentation#3485]
Re: [Role-Based Permissions & Change Management](https://pantheon.io/docs/change-management/)

Priority (Low‚ Medium‚ High): Low

## Issue Description:
Currently, only Org Admins can update the assigned role of a User. This is not clearly stated in our doc.
This confuses Team Members because they can add new Users but they don't have the permission to update the user role once added.

<img width="879" alt="a" src="https://user-images.githubusercontent.com/14119666/37691411-cc96ba16-2cec-11e8-92b6-2e12563edcb7.png">

## Suggested Resolution
Include "Manage User Role" in the permission list or add this to our FAQ section.

**Comment by rachelwhitton** [comment]
Thanks for reporting @rubelyn, much appreciated 

I'm going to defer to product here because tbh this has always been a point of confusion for me. Will address once guidance is provided there. @slivermon can you point me in the right direction? Who can I work with on this? Or should it be closed and worked as part of future product sprints?

**Comment by rachelwhitton** [comment]
Thanks for the clarification @slivermon! We definitely expect heavier edits around this in the coming months.

For now, we'll continue work on this issue by:
- Deleting "Manage site-level team"
- Adding "Manage User Roles", a permission granted only to Org Admins 
- Adding "Invite New Team Members", a permission granted to Org Admins & Team Members
