### ISSUE TITLE
WordPress Configuration Management (WP-CFM) Doc Update 

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3486]
Re: [WordPress Configuration Management (WP-CFM)](https://pantheon.io/docs/wp-cfm/)

Priority (Medium):

## Issue Description:
A customer followed the steps here and it seems to be no longer working. It may be because of the new version updates at core where it is no longer compatible.

## Suggested Resolution
Review and revamp if this docs is still applicable or deprecated.

**Comment by eabquina** [comment]
Tried the plugin in the a new site and in general, **it works**, Worth adding a Troubleshooting section related to CLONE operation in between environments.

For one specific issue: You can create WP-CFM bundles in TEST or LIVE. Bundles are saved in wp_options table before its "pushed" to a config .json file. Because of this, it might be confusing if someone creates bundles in TEST or LIVE, as it will overwrite your bundle configuration when you CLONE the database around. Also, It lets you click the "Push" button, but it doesn't create anything in TEST or LIVE. 

There should be a warning in the docs about this is something that we should not touch in TEST or LIVE, and be strict with the workflow.

Also, maybe we can make use of wp-config.php and add a configuration where we can LOCK this feature in TEST or LIVE environment so the database wpcfm_settings field will be consistent. Not sure though yet if this is possible.

**Comment by alexfornuto** [comment]
Thanks for the issue @eabquina!

We're going to mark this as low priority. As far as action to be taken, we'll add some callout (type TBD) to the front of this guide warning readers that:

 - Saving configurations is only possible in the Dev and multidev environments, since the code base is locked in the others
 - Cloning databases before saving configurations to the code base can result in loss of data.
