### ISSUE TITLE
Include instructions for wkhtmltopdf.

### ISSUE THREAD

**Issue by karenpantheon** [pantheon-systems/documentation#3607]
@pantheon-systems/cse
Priority (Low‚ Medium‚ High):

## Issue Description:
A customer was trying tcpdf to generate larger files but is unsuccessful. Issue was only resolved when she switched to wkhtmltopdf.

## Suggested Resolution 
Include instructions for wkhtmltopdf and also include in the doc that this library is already installed by Pantheon. From the customer:

I just wanted to point out, it would have been helpful if you had known that this library was already installed by Pantheon and instructions were available in the docs. Would have saved me several hours of work. 
https://pantheon.io/docs/external-libraries/#wkhtmltopdf 

https://pantheon-systems.desk.com/agent/case/103329

**Comment by alexfornuto** [comment]
@karenpantheon there are a few "issues" with this issue:

1) What doc are you suggesting we edit?
2) As your first link shows, we already document that the library is installed. What our docs don't cover is how to install and configure individual modules. Is there something pantheon-specific that needs to be included in the linked section of "External LIbraries" in order to get it working that isn't already there?

I guess what I'm asking is "what new information needs to go where to make your job easier?"
