### ISSUE TITLE
Additional FAQ about backups

### ISSUE THREAD

**Issue by ruthiehallarsis** [pantheon-systems/documentation#3661]
Priority: Low

## Title
Additional FAQ about backups

## Description
Will my site be affected when creating/running a backup workflow? or does backup affect site performance when running

* i got a chat about this. A plugin was acting weird suddenly at the same time while creating a backup. 
https://app.intercom.io/a/apps/xkegk7cr/inbox/inbox/1953825/conversations/16188184979

## Expected Audience
All customers who use our backups tool.

## Path
https://pantheon.io/docs/backups/

**Comment by ttrowell** [comment]
When a backup runs, there are three parts.  Usually, the database and code backups complete first and the files take the longest time depending on the size of the file repository.   The backup process itself has little impact on the site, however, the size of each element of the backup has to be taken into consideration.   

Best practice is to run backups during off-hours when there is no development or much traffic.  The downside here is that setting the backup time is not straight-forward.  You have to literally enable and disable it until it lands on an acceptable time.

**Comment by alexfornuto** [comment]
I feel like this is all covered by [this existing FAQ answer](https://pantheon.io/docs/backups#what-can-i-do-during-backups)

The chat referenced concluded that the issue was coincidental with the backup being run.

I'm going to close this issue. @ruthiehallarsis feel free to open it back up if you want to provide more specifically what you think needs to be added to this doc.
