### ISSUE TITLE
Pantheon YAML Configuration Files Doc Update 

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/documentation#3771]
Re: [Pantheon YAML Configuration Files](https://pantheon.io/docs/pantheon-yml/)
https://pantheon.io/docs/pantheon-yml/#filemount-path

Priority (Low‚ Medium‚ High): Medium?

## Issue Description:  I'd like maybe get some advanced use cases for altering this file because it seems that most users should not edit this location.  
1. When should this setting be used?
2. Does this automatically create a symlink?
3. What kinds of errors could happen if the location is set improperly and how can CSE check to verify if the setting made in the yml file is problematic?

**Comment by alexfornuto** [comment]
CC @ari-gold

**Comment by greg-1-anderson** [comment]
1. This setting is useful only when making a custom upstream e.g. backdrop
2. Yes the purpose of this file is to create the symlink - that's all that it does
3. There are a number of things that must be set consistently for this setting to work correctly, as described in the documentation. If the .gitignore is not right etc. there may be various side effects. This is why it's best to only make the change in an upstream, because moving the link from one location to another in an existing site can cause other issues (e.g. hardcoded paths to file assets in the database, etc.)
