### ISSUE TITLE
Why does Pantheon recommend using CNAME records?

### ISSUE THREAD

**Issue by umandalroald** [pantheon-systems/documentation#3798]
Priority:

## Title
Why does Pantheon recommend using CNAME records?

## Description
Advantage of using CNAME over A record and why we recommend to use CNAME.

## Expected Audience
Site Owner/Developer

**Comment by alexfornuto** [comment]
@umandalroald what doc is this referring to?

**Comment by alexfornuto** [comment]
I don't think a new doc is required here. I think we should:

1. Make a partial file that explains that pointing custom domains to our platform domains via CNAME records is preferred because it tolerates IP address changes, which are more likely to happen than platform domain changes.
2. Add the partial file to any of the following possible locations:

 - Launch Essentials - [Configure DNS and Provision HTTPS](https://pantheon.io/docs/guides/launch/configure-dns/)
 - [Platform and Custom Domains](https://pantheon.io/docs/domains/)
 - [Introduction to Domain Name Services](https://pantheon.io/docs/dns/)

**Comment by alexfornuto** [comment]
As described in #4334, this issue is no longer relevant.
