### ISSUE TITLE
Using WP SAML Auth with Google Apps Doc not beginner friendly 

### ISSUE THREAD

**Issue by Pimmetje** [pantheon-systems/documentation#3844]
Re: [Using WP SAML Auth with Google Apps](https://pantheon.io/docs/wordpress-google-sso/)

Priority (Low):

## Issue Description:
As a wordpress and SAML beginner i would like to see enough information to get the login working. Preferably with a group check. 

The google part is very clear. I have all the data i need from that side. 

However the wordpress site part is unclear. There is sample code shown. But i can't identify the file where this information has to come. Also i have a feeling it does not add a button to the UI for redirecting to the IDP. How do i add this button to wp-login.php?

## Suggested Resolution \

Please add some more information to the sample to get beginners started.

**Comment by danielbachhuber** [comment]
@alexfornuto It can be added to the theme's `functions.php` file, or a mu plugin.

**Comment by alexfornuto** [comment]
@danielbachhuber please clarify: Are you saying it can be added to an existing mu plugin, or that one should be created to hold this code?

If the former, can you suggest any plugins for the job?

If the latter, could a beginner use a tool [like this](https://wordpress.org/plugins/mu-plugins-tool/) for the task at hand?

**Comment by danielbachhuber** [comment]
It's the latter, however I don't think using a plugin for this is necessary. Here's some additional context on what I'm referring to:

* https://themeisle.com/blog/wordpress-functions-php-guide/
* https://www.wpbeginner.com/beginners-guide/wordpress-plugin-vs-functions-php-file-which-is-better/

The advantage of a mu plugin is that it remains active when you switch themes, because it's independent on the theme code. If you were to put the code snippet in a `functions.php` file, it would only remain active when the theme was active.

**Comment by Pimmetje** [comment]
Sorry for the late reply. Thanks for the information ill try it if i find anything else missing ill reopen this ticket.
