### ISSUE TITLE
Migrate Sites to Pantheon Doc Update — Drush 9 "ard" command

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#3946]
Re: [Migrate Sites to Pantheon](https://pantheon.io/docs/migrate/)

Priority (Low‚ Medium‚ High): Medium

## Issue Description:
We recommend using `drush ard` to export a Drupal site for migration.  `drush ard` does not exist in Drush 9 currently (see https://github.com/drush-ops/drush/pull/2532 / https://drupal.stackexchange.com/a/250782).

## Suggested Resolution
Suggest users either downgrade to Drush 8 to run that command, or create an archive manually (and note the structure it requires).

Internal ref: #111161

**Comment by alexfornuto** [comment]
The removal of `ard` from Drush 9 could impact this doc in a lot of ways. CC @greg-1-anderson to help understand the impact on migrating sites to Pantheon without `ard`.

**Comment by alexfornuto** [comment]
Blocked pending CORE-448

**Comment by greg-1-anderson** [comment]
Manually creating an archive would be error-prone. We should not document this, as the support requirements would be too high.

Advising users to use Drush 8 is workable; note, however, if there is a site-local Drush included in the site, then Drush will *always* use it. Therefore, site-local Drush users will need to downgrade the Drush that is inside their site, or remove it entirely.

Some users may be reluctant to downgrade Drush, because Drush 8 is not officially supported on any version of Drupal after Drupal 8.3.x.  It is known to work on Drupal 8.4.x and 8.5.x.

**Comment by krisrobinson** [comment]
Found this issue searching to figure out how to do `ard` in drush 9 when migrating a Drupal 8 site to Pantheon. I think its pretty lame to require to downgrade drush to 8 when it's not even technically supported on my version of Drupal.  Surely there's a better solution here?

**Comment by alexfornuto** [comment]
Update: No action yet on CORE-448.

**Comment by jimcraner** [comment]
What's involved with manually creating an archive file?  It's just a mysqldump and a tarball of the file tree, right, or is there something I'm overlooking?

**Comment by greg-1-anderson** [comment]
I'd recommend looking at the source for Drush 8 if you want to break this down. I think it would be error-prone and subject to high support requests.

Note that you **can** use Drush 8 to make an archive of a Drush 9 site (as long as it is not Composer-managed), import it into Pantheon, and then switch to Drush 9 once you are done.

n.b. Drush 9 is not officially supported on Pantheon yet. It's available to preview for those who are interested.

**Comment by EdwardAngert** [comment]
@ari-gold, @alexfornuto and I are trying to find a way to move a solution forward on this (and re: CORE-448). any recommendations?

**Comment by greg-1-anderson** [comment]
My comment above is erroneous, as a "Drush 9 site" is by definition Composer-managed. If you have a Composer-managed site, though, then you do not want to use the dashboard to import the site anyway.

So, the workaround for the moment, for non-Composer-managed sites, is to use Drush 8 to create the archive dump. I think that the way forward for this issue is to make the documentation explicit that Drush 8 must be used to create the archive dump.

Documentation updates for Drush 9 + ard can be done after CORE-448 is pulled into a sprint.

**Comment by greg-1-anderson** [comment]
The actual blocking issue is [CORE-681](https://getpantheon.atlassian.net/browse/CORE-681), which is a follow on to CORE-448, which is just a PoC. I added another "done when" to CORE-681 to open a docs issue or PR to give the docs team guidance once archive dump is available using Drush 9.

**Comment by EdwardAngert** [comment]
wonderful, thanks @greg-1-anderson!
