### ISSUE TITLE
Visual Composer Plugin Compatibility

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/documentation#3975]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/modules-plugins-known-issues/)

Priority (Medium):

## Issue Description:
Chat IDs: 17820246104, 178202x
Visual Composer plugin had some changes for the past year. There are now two versions of the plugin that can be used for WordPress

The original and commonly bundled plugin is now called "WPBakery Page Builder" wpbakery.com, while a new and separate product is made known to be the new Visual Composer (visualcomposer.io). 
https://visualcomposer.io/docs/faq/visual-composer-website-builder-vs-wpbakery-page-builder/

For the Visual Composer (.io) version, they released 2.8 last July 18, 2018 and take note 
2.8 – 18.07.2018
Fix: Visual Composer works properly on Pantheon hosting
https://visualcomposer.io/docs/release-notes/

Testing the two plugins, shows that they can work in TEST or LIVE environments of a site.
http://live-visualcomposer.pantheonsite.io/
We are using the default WP theme, and free versions of both. 

## Suggested Resolution

Modify the plugin section to identify them as two different plugins (WPBakery Page Builder vs Visual Composer)

Review possible issues that would cause Visual Composer not to work:
- Plugin unable to save due to the bundled Theme
- Changes that are saved only in the DB, and might need an import/export tool like WP-CFM to send changes to TEST/LIVE

**Comment by alexfornuto** [comment]
@eabquina Visual Composer Page Builder does _not_ work on Pantheon, as I've tested and documented on #3805.

**Comment by alexfornuto** [comment]
And apparently I'd have to buy WPBakery Page Builder before I could test installing it.

**Comment by alexfornuto** [comment]
@eabquina BTW it appears that there is no longer a free version of the WP Bakery plugin with which to test.

**Comment by say2me** [comment]
WP Bakery plugin had never been free.
Visual Composer Website builder is free.

**Comment by alexfornuto** [comment]
@say2me [this comment](https://github.com/pantheon-systems/documentation/pull/3805#issuecomment-415451864) details where I left off testing Visual Composer Website Builder.

**Comment by carl-alberto** [comment]
@say2me I'm also interested in getting this clarified and documented in Pantheon if possible:

1) It seems **[WP Bakery plugin](https://kb.wpbakery.com/docs/preface/release-notes/
)** and **[Visual Composer Website](https://visualcomposer.io/docs/release-notes/)** two different products and codebase basing from their changelog, do they also have different license which needs to a separate product noted in the docs? 

2) In terms of licensing, will single site license work in Pantheon where theoretically there are 3 sites/url they will be juggling with (dev, test and live)? Or will users need a developer license for this to avoid issues?

3) By design, page builders work well in single environment hosting where people got used to in editing directly their live site, in Pantheon, first time page builder users tend to do a lot of page editing in the  DEV environment, then clone their db up to LIVE unknowingly overwriting important live data. Users realizing that, painfully copying and pasting page by page their changes from DEV upto LIVE. Would there be a recommended way in using Visual Composer so users can easily deploy their changes from DEV upto LIVE to match our recommended [workflow](https://pantheon.io/docs/pantheon-workflow/#code-moves-up-content-moves-down)? It would also benefit Visual Composer users in Pantheon if there is a good documentation outlining the best way in deploying their changes/edit to match the workflow.

**Comment by eabquina** [comment]
@say2me  After testing at Ticket: 113841, we were able to confirm that by default, it is not working.
However, by adding in wp-config the FS_METHOD to be **direct**, it is now working.

`define('FS_METHOD', 'direct');`

As opposed from the the CMS Admin docs, adding this might have negative effects on OTHER plugins.
This might need some testing. 
https://pantheon.io/docs/cms-admin/#unable-to-install-plugins-on-migrated-sites

But as a recommendation from the developer, as it works on DEV/TEST, we can try to explicitly add this 

```
 if ($_ENV['PANTHEON_ENVIRONMENT'] === 'test' || $_ENV['PANTHEON_ENVIRONMENT'] === 'live' ) {
    define('FS_METHOD', 'direct');
  }
```

Next steps, to review if this will be fine, no negative effects on other plugins or installation methods.
Also validate if applicable to WPBakery Pagebuilder.

**Comment by alexfornuto** [comment]
@eabquina please continue discussion in #3805
