### ISSUE TITLE
Use the Pantheon Workflow Doc Update [Components > Code]

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#4017]
Re: [Use the Pantheon Workflow](https://pantheon.io/docs/pantheon-workflow/)

Priority: Low

## Issue Description:

We show the directory structure for Drupal and WordPress here: https://pantheon.io/docs/pantheon-workflow/#code. The Drupal tab shows Drupal 7, which is outdated. The WordPress tab is missing some WP core files, this is maybe outdated as well.

## Suggested Resolution

Remove the directory listings. Maybe link off to our code repos on Github or find a different way to explain what exactly "code" refers to.

**Comment by alexfornuto** [comment]
@sarahg Why do you propose removing the directory listings instead of updating them?

**Comment by xq42** [comment]
@alexfornuto - My assumption is this would then always be up to date since they'd be looking at "live" versions of core for WP / D7 / D8.

FYI, when I answer this question in chats, I typically phrase it this way:

- "files" is anything inside of wp-content/uploads (sites/default/files)
- "code" is anything outside of wp-content/uploads (sites/default/files)

Since there is some "code" in that construction that is not held in git, this is a small bit less _accurate_, though it seems to be very _useful_ for the folks I'm helping...

In the context of this doc, I don't think my formulation would be sufficient by itself, but I also don't see the utility of having the current example structures there either. My impression is that most folks who don't know the structure of a WP or Drupal codebase aren't likely to understand what they're being shown.
