### ISSUE TITLE
Document how to connect to a live site via SFTP 

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#409]
Story:
As a Pantheon User I want connect to my live site via SFTP so that I don't see errors being bounced between servers. 

When users connect with some FTP clients:

FileZilla
Yummy
CyberDuck
They are using the application's default settings and for Pantheon that can cause some issues. They need to set their connection limit to 1 and then connect, that way they will not get errors while on their live site.

Screenshots of where the settings are for each client:

Yummy FTP Client: https://www.evernote.com/shard/s203/sh/c58733b1-b259-429a-ad5d-71eb9d05b3e7/ce06c2c099616b536043807492ee5dfc
FileZilla: https://www.evernote.com/shard/s203/sh/f1fa6054-c557-436e-be31-53c7a74981bc/fba13129d7c06468462f918d1a0291bd
CyberDuck: does not have a setting I can find

submitted by @atjuch

**Comment by nataliejeremy** [comment]
@atjuch Is this the doc you're referring to? https://pantheon.io/docs/articles/sites/code/developing-directly-with-sftp-mode/

Do you have any example error msg for "errors being bounced between servers"? If not, can you tell me the use case/condition when the user gets the error?

**Comment by ttrowell** [comment]
This request may need review.  I do not think that we allow clients to SFTP to their live sites.  SFTP is only allowed on Dev for development and then changes/additions are pushed up via Git.  Files added to standard upload paths via the CMS are, of course, allowed.

Clarifications/instructions on how to use various SFTP clients makes sense, but not for the purpose of accessing the test or live environment.

**Comment by bmackinney** [comment]
@ttrowell the use cases are for access to `files` and to verify code deployments (if in doubt)

**Comment by suzannealdrich** [comment]
It's definitely possible for clients to connect via SFTP to their live sites. They can even write to the /files directory, just not to the /code directory, for the reasons @ttrowell stated. However, many users have problems when connecting using their clients to upload to /files because there are multiple application servers to which they can be connecting. This manifests as a report of a folder not being found, because the absolute path of the home directory has a different UUID per application server. Limiting the number of simultaneous connections to a maximum of one mitigates this issue as well.

**Comment by bmackinney** [comment]
@suzannealdrich please verify that #585 is sufficient. If not, please add a commit to the PR.
