### ISSUE TITLE
Modules and Plugins with Known Issues Doc Update 

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/documentation#4523]
Re: [Modules and Plugins with Known Issues](https://pantheon.io/docs/modules-plugins-known-issues/)

Priority: Low

## Issue Description:
There are different recommendations for the Autoptimize plugin on these two pages:
https://pantheon.io/docs/guides/frontend-performance/#use-as-few-requests-as-possible
https://pantheon.io/docs/modules-plugins-known-issues/#autoptimize

Which one is correct?

## Suggested Resolution
Figure out which recommendation we need and fix the other one.

**Comment by alexfornuto** [comment]
@sarahg seems to me that neither is technically correct (the best kind of correct), and either path works as an alternative to the defined path to the code base.

I'm leaning towards standardizing on the path `/uploads/autoptimize/`since it's a) more descriptive than `resources` and b) we already have a screenshot showing that example and I'm lazy.

Unless you have any objections I'll update the Frontend Performance guide to match.

**Comment by sarahg** [comment]
@alexfornuto Sounds good, I like `uploads/autoptimize` better as well. I'd also remove `AUTOPTIMIZE_CACHEFILE_PREFIX` from the Front-end Performance Guide since that isn't really necessary for the plugin to work on the platform.

**Comment by alexfornuto** [comment]
@sarahg while not required, I assume it's in that guide because it helps with frontend performance. Unless there's a specific reason to remove it, I'd defer to the authors of the guide and leave it in.
