### ISSUE TITLE
Using SendGrid To Deliver Email Doc Update 

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/documentation#4559]
Re: [Using SendGrid To Deliver Email](https://pantheon.io/docs/guides/sendgrid/)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:
Suggested D7 installs 7.x.1.x-dev version of sendgrid module, is that still recommended? Can you provide context for why this is recommended vs the official release version? 

## Suggested Resolution

**Comment by rachelwhitton** [comment]
I went through the process a few times today, first as prep work; I installed 7.x.1.x-dev version, second time was live with a client and their preference was to use sendgrid_integration-7.x-1.3 so we did that and found that it works. 

I think my suggested resolution here is to update D7 instructions so that current release is used instead of dev release, to promote best practices in regards to not using dev releases in prod

**Comment by alexfornuto** [comment]
Thanks @rachelwhitton. I can't say why we specify that version, that's how @dustinleblanc wrote it when he added this documentation. I imagine he had a good reason at the time.

Since you said that you tested and found 7.x-1.3 to work, I'll update the doc to use that version, and consider your setup with the client technical validation.
