### ISSUE TITLE
Launch Essentials Doc Update 

### ISSUE THREAD

**Issue by ccorpus** [pantheon-systems/documentation#5046]
Re: [Launch Essentials](https://pantheon.io/docs/guides/launch/plans)

Priority: Medium

## Issue Description: 
This appears outdated. Also, is this meant only for online customers? If you're a contract customer, credit cards are not relevant to the launch process. 

## Suggested Resolution:
For online customers, upgrading and selecting a site plan should more closely resemble the process here: https://pantheon.io/docs/site-plan#purchase-a-new-plan. This is similar for contract customers, but it should be clear that any mention of credit card use should be ignored in the doc.

**Comment by EdwardAngert** [comment]
@ccorpus it looks like the steps are accurate for credit card customers, and I see what you're saying about it not being relevant to our contract customers, save for the last sentence on the bottom:
> Resellers and Enterprise organizations should contact their Account Manager or create a Support ticket to request a transfer of ownership.

I can put a better version of that at the top so that contract customers don't bother trying to read through a page that isn't for them. Do you have a suggestion for a doc that Contract should be referencing, or should we just direct them to their Account Manager?

**Comment by alexfornuto** [comment]
> This appears outdated. 

Not enough information to be useful.
