### ISSUE TITLE
Enabling Solr for WordPress Doc Update 

### ISSUE THREAD

**Issue by brenda003** [pantheon-systems/documentation#5298]
Re: [Enabling Solr for WordPress](https://pantheon.io/docs/wordpress-solr)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:

Clicking on the sidebar of this page doesn't jump me to the corresponding section of the page. Example, clicking on "Known Issues/Limitations" on the right sidebar brings me to "Install and Configure Plugin" in the content area.

## Suggested Resolution

**Comment by alexfornuto** [comment]
@brenda003 thanks for reporting! Unfortunately this isn't something I can fix yet, it's a problem with how  Gatsby and MDX work together (logged as an issue [here](https://github.com/gatsbyjs/gatsby/issues/18000)). 

I'm going to close this for now since resolution is outside of the team's reach, but the link above will reference it on the Gatsby issue, so once that's resolved I can go back and check this page along with the others affected.
