### ISSUE TITLE
Developing on Pantheon Directly with SFTP Mode Doc Update 

### ISSUE THREAD

**Issue by sparklingrobots** [pantheon-systems/documentation#5472]
Re: [Developing on Pantheon Directly with SFTP Mode](https://pantheon.io/docs/sftp)

Priority: Low

## Issue Description:
The term "Binding path" isn't immediately clear to customers who are trying to find their code, so the header "How do I find my site's Binding path?" doesn't help when their SFTP client doesn't open the right directory.

## Suggested Resolution
What if we changed the heading to something like "I can't find my site code directory" or something similar?

**Comment by rubyji** [comment]
If possible, it would also be incredibly helpful to include the binding path in the SFTP info that is available on the dashboard.

**Comment by alexfornuto** [comment]
We'll change the header to use "remote path" instead of "binding path", and defined binding path in the body.

**Comment by rubyji** [comment]
I know this is closed but I have a suggestion and I don't know where to put it. Feel free to redirect me. 

Where you have [the suggestion for finding your binding path](https://pantheon.io/docs/sftp#how-do-i-find-my-sites-remote-path) it would be helpful to offer the specific command for connecting to SFTP to get the binding path. 

I only use SFTP mode for very simple tasks, like updating modules on D7, so so this adds a whole other step to what should be a quick process. In the situation where I find myself at the top-level instead of my own directory, I'm usually connecting via GUI FTP client. So now I have to figure out the command-line syntax for FTP-ing, etc. I have spent much too much time on this because it happens to me nearly every time I set up a new multidev branch.

**Comment by alexfornuto** [comment]
@rubyji So there isn't really a great answer to "make your SFTP client connect to the correct binding path". It either does it automatically or not. In my case, I use Filezilla when I need to SFTP and it recognizes the path it should put me in.

I know this isn't the answer you want to hear, but there's hope yet! There are a few things to consider:

- Product changes on the horizon should solve this issue soon, changing the binding path to something much more simple and immediate.
- If you're just using SFTP mode to update modules, you could instead stick to Git mode, and use Drush over terminus to update modules remotely. The command would be something like:

```
terminus drush site.env -- up modulename
```

**Comment by rubyji** [comment]
Thanks, @alexfornuto.  I'm not using Terminus with this site (it's Drupal 7), and Drush never seems work consistently even within Lando. I'll get it working and then a few weeks later I go to use it, and Drush or Lando is throwing errors again. It's not worth my time to troubleshoot every time, which is exactly why I use a quick & dirty SFTP client instead.

**Comment by alexfornuto** [comment]
Fair enough. I'm not a Drupal user, so I'm out of my depths to speak to that (CC @carolyn-shannon).

In any case, binding paths should be getting real simple real soon, stay tuned...
