### ISSUE TITLE
Drupal Modules - ReCAPTCHA SERVER_NAME

### ISSUE THREAD

**Issue by carolyn-shannon** [pantheon-systems/documentation#5634]
Re: [Drupal Modules with Known Issues](https://pantheon.io/docs/modules-known-issues)

Priority: Low

## Issue Description:
- The Drupal ReCAPTCHA module (Drupal 7 and 8) is among the modules that use the `SERVER_NAME` variable, which can [generate errors](https://pantheon.io/docs/server_name-and-server_port#use-http_host-instead-of-server_name).

## Suggested Resolution

- Add a note to the Drupal Modules page [entry](https://pantheon.io/docs/modules-known-issues#recaptcha) for the ReCAPTCHA module.
- Add the ReCAPTCHA module to the [list of known modules](https://pantheon.io/docs/server_name-and-server_port#known-pluginsmodules-using-server_name) that use `SERVER_NAME`.

**Comment by alexfornuto** [comment]
Resolved directly into master, because I R stoopid. Commits for reference:

- https://github.com/pantheon-systems/documentation/commit/585a75432fe1e4bd76debff5f78843a06e10d805
- https://github.com/pantheon-systems/documentation/commit/ccff5f25824e7a265c309a86e004f92a8d10eeab
- https://github.com/pantheon-systems/documentation/commit/25e9cd8c592aec3d0197b1641b0b9a394845bcb3
