### ISSUE TITLE
WordPress Best Practices Doc Update add how to Secure wp-admin and wp-includes folder

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/documentation#5702]
Re: [WordPress Best Practices](https://pantheon.io/docs/wordpress-best-practices)

Priority: Low

## Issue Description:
Add how to secure wp-admin and wp-includes folder

## Suggested Resolution
upcoming PR for discussion

**Comment by carolyn-shannon** [comment]
@carl-alberto wouldn't securing wp-admin via protected path disable access to wp-admin?

**Comment by carl-alberto** [comment]
Ah yeah, sorry about that @carolyn-shannon 

I might need to be more specific if that is the case of the wp-admin folder files that when accessed directly reveals the paths eg:
https://example.pantheonsite.io/wp-admin/custom-header.php
https://example.pantheonsite.io/wp-admin/includes/admin.php
https://example.pantheonsite.io/wp-admin/user/menu.php

So would it be better if we can have a list of those files if they are not meant to be accessed directly?

**Comment by carolyn-shannon** [comment]
@carl-alberto I'm not sure what exceptions would need to be in place for this to reliably work. Do you know anyone who has used protected paths to achieve this? 

Otherwise, does it make more sense to document the plugins commonly used to achieve this (eg iThemes' Security, WPMU Dev's Defender?) and maybe refer to the WP Best Practices section of the Optimize Site Traffic page re login limits & honeypots (https://pantheon.io/docs/optimize-site-traffic#wordpress-best-practices), and maybe the note on plugins that manage private paths (https://pantheon.io/docs/private-paths#plugins-that-manage-private-paths)?

**Comment by carl-alberto** [comment]
@carolyn-shannon not really sure too because I have been trying to raise those files that throw errors when directly accessed to the WP core team https://core.trac.wordpress.org/ticket/49499#comment:4. I believe there are no plugins that can detect them as they are direct file calls bypassing WP and was replied them that the mitigation should be in the hosting level https://core.trac.wordpress.org/ticket/49499#comment:5 so most likely the one that we can suggest is using the same method as the solution on how to protect xmlrpc https://pantheon.io/docs/wordpress-best-practices#disable-xml-rpc-via-pantheonyml

**Comment by EdwardAngert** [comment]
closing based on the conversation in #5703
