### ISSUE TITLE
Using Lockr to Secure and Manage API and Encryption Keys Doc Update 

### ISSUE THREAD

**Issue by benjaminbradley** [pantheon-systems/documentation#6071]
Re: [Using Lockr to Secure and Manage API and Encryption Keys](https://pantheon.io/docs//guides/lockr)

Priority: Medium

## Issue Description:
Step 1 fails in the workflow **Clone the Lockr Terminus plugin into the ~/terminus/plugins directory on your local environment.**
**Clone the Lockr Terminus plugin into the ~/terminus/plugins directory on your local environment.** results in the error:

> Could not load plugin lockr/lockr-terminus because it is not compatible with this version of Terminus.

I submitted an issue for the plugin: https://github.com/lockr/lockr-terminus/issues/6

## Suggested Resolution
I see that the doc was written by Chris Teitzel / Cellar Door, the company which created the Lockr service. Maintenance of the plugin should be their responsibility.

I see Pantheon's responsibility here as providing current documentation for a way to securely store and retrieve secret credentials for a site hosted on the Pantheon infrastructure, whose integration will be supported by Pantheon. That could mean getting Lockr working with the current version of Terminus, or providing an alternate path to satisfy the same use case.

**Comment by alexfornuto** [comment]
Thanks for letting us know @benjaminbradley! We'll reach out to Lockr to make sure they see the issue you've logged with them.

**Comment by cellar-door** [comment]
We're tracking the issue on the plugin repo and should have more updated there shortly.

It may be worth revisiting the documentation on this as the terminus plugin isn't a required step for Drupal 8 and beyond as much of the terminus integration was to automatically patch modules in order to have them work with the Key module. But in Drupal 8/9 this isn't as necessary due to the config entities which Key can create to override.

I'll take it on myself to re-write this section and provide an updated workflow.

**Comment by whitneymeredith** [comment]
@cellar-door Closing this issue here since you are taking care of it on your repo.
