### ISSUE TITLE
Convert an existing Drupal 8 site to use Integrated Composer

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#6117]
Re: Converting an existing Drupal 8 site to use Integrated Composer

Priority: Medium

## Issue Description

Existing sites that wish to upgrade to Drupal 9 and convert to Integrated Composer, or just convert to Integrated Composer and defer the Drupal 9 upgrade will need to go through some manual steps. This conversion process may be automated in the future, but initially we will need to document the manual process.

## Suggested Resolution

The steps outlined below should for the most part work fairly well. Some small adjustments to the steps may still be needed; validation is required.

FYI: In the instructions below, note that `git checkout <branch> <file|dir>` copies a file or directory from another branch to your current branch without changing branches. This is a useful technique when migrating or converting code on a new branch.

- Add a new remote for the ic upstream and put it on a new branch, “comoserify”

```
git remote add ic git@github.com:pantheon-upstreams/drupal-project.git
git fetch ic
git checkout -b composerify ic/master
```

- Copy your configuration from the default branch

```
git checkout master sites/default/config
git mv sites/default/config/* config
git commit -m 'Pull in configuration from default branch'

```

- Compare your pantheon.yml with the new pantheon.upstream.yml and check for conflicts

```
git diff master:pantheon.yml pantheon.upstream.yml
```

- If you need your pantheon.yml, copy it over (be sure to edit if needed):

```
git checkout master pantheon.yml
# edit as needed
git add pantheon.yml
git commit -m 'Copy my pantheon.yml'
```

- OPTIONAL: Return to Drupal 8 if you’re not ready to update to Drupal 9 yet. (Advisable: test the Composer conversion before testing the Drupal 9 upgrade)

```
composer require drupal/core-recommended:^8
git add composer.*
git commit -m 'Revert to Drupal 8'
```

- Survey your enabled modules:
```
terminus drush site.dev -- pm:projectinfo --fields=name,version --format=table
```
- For each module in the list, use `composer require` to add it to your new site

  - For entries similar to “Address (address) 8.x-1.8”: `composer require drupal/address:^1.8`
  - For entries similar to “Devel (devel) 4.0.1”: `composer require drupal/devel:^4.0.1`
  - Add a ^ in front of the version to indicate “this version or any later version”
  - You may put all of the modules on a single line, if you prefer. This is faster.
  - Skip the “drupal” line. Never install drupal/drupal via Composer.
  - Skip drupal/ludwig, if your site is using it.

- Add any custom code you might have
```
git checkout master modules/custom
```

- Bring over your settings.php customizations
```
git checkout master sites/default/settings.php
mv -f sites/default/settings.php web/sites/default/
git rm -rf sites
git diff
```
_IMPORTANT: If your settings.php file has database credentials in it, be sure to remove them. Usually, credentials are not committed to settings.php, so this should not be an issue._
- You might want to add this to your settings.php file:
```
$settings['config_sync_directory'] = '../config';
```
- Create a multidev for your new working branch
```
terminus env:create $site.dev composify
```
- Force push and pray
```
git push origin --force composerify
```

**Comment by EdwardAngert** [comment]
for me for later, I think this is the doc for this: https://pantheon.io/docs/guides/composer-convert

**Comment by greg-1-anderson** [comment]
That's right @EdwardAngert ; the doc you linked to gives instructions on how to convert to the Terminus Build Tools workflow. Once Integrated Composer is ready, this doc should be rewritten following the suggested template above, once it is tested and validated.

Another thing of note is the current document contains this advice:
```
find . -maxdepth 2 -name '*.info.yml' \
  -exec basename '{}' '.info.yml' ';' \
  -exec grep -e '^version' '{}' ';' \
  -exec echo ';'
```
I instead recommended using:
```
terminus drush site.dev -- pm:projectinfo --fields=name,version --format=table
```
If `terminus drush` isn't available, the `find` + `grep` solution might be useful, so you could consider including both techniques to give the user more options.

**Comment by EdwardAngert** [comment]
linking this comment from #5663 
https://github.com/pantheon-systems/documentation/pull/5663#issuecomment-702397024

**Comment by mbaynton** [comment]
I'm going through these instructions as a test of them.

> Compare your pantheon.yml with the new pantheon.upstream.yml and check for conflicts

Is the point of this step to build awareness of any settings you might have had in your old `pantheon.yml` that are not also present in the new `pantheon.upstream.yml` and, if there are any, include them in a new `pantheon.yml`?

**Comment by greg-1-anderson** [comment]
Yes, that step is just to make sure that folks do something rational with any customizations.

**Comment by hanoii** [comment]
I was given the task to look for a better composer approach for a regular pantheon site. I was going to play around with GitHub actions which I already did it with an Acquia project and came across integrated composer and this issue.

Although I took pointers of this issue what I did was spin up a new d9 as per the [doc](https://pantheon.io/docs/integrated-composer) and downgrade it locally by running

```
composer require drupal/core-recommended:^8.9 consolidation/robo:^1.4 consolidation/site-process:^2.1 -W
```

After pushing this I was able to install the latest Drupal 8 on pantheon. (I did got a fatal error `Uncaught PHP Exception InvalidArgumentException: "Class "Drupal\views\Routing\ViewPageController" does not exist."`, but fixed it with a `terminus clear-cache` command).

From thereon I guess I can bring  over the config/database of the original project I can convert into integrated composer or maybe attempt to do it place on the original project.

I am still evaluating GitHub actions but I'd like to ask a few questions around this as there are not a lot of documentation yet.

- Is there a preference between doing it like this (new project) as opposed to the original description of this issue (old-school pantheon d8)?
- I wonder about the benefits of the one-click updates on this use case. I assume that you will update your `upstream-configuration/composer.json` to bring in updates, is that so? or is there other means going on behind the scenes?  If I downgraded, would I still get one click updates for say 8.9.14 when it's out?
- What happens for regular module dependencies, are those supposed to be handled as one-click updates?
- And finally, I think - I was worried about the artifacts being added to the repo and the size of it. But I see that you are just adding them as orphaned tags and as you are using the same tag the size of the repo built artifcats would always be 1x of the latest built. I found it odd that a new `git pull` wouldn't bring me the latest tag but cloning it on a separate doc did, in a way I prefer this, it was just counterintuitive. Is this because it's the same tag name (although of different commit hash)?

**Comment by greg-1-anderson** [comment]
- The advantage of creating a new site instead of migrating an existing site is that with a new site, you get Mariadb 10.4, whereas at the moment existing sites are still on Mariadb 10.0.  The advantage of converting an existing site is that it is slightly fewer steps, and you don't need to move your domain settings.  In the future, existing sites will be able to be upgraded to Mariadb 10.4.
- One-click updates are available with Integrated Composer sites. Don't modify anything in upstream-configuration unless you make your own custom upstream based on the D9 IC template project. In that instance, you would add modules to upstream-configuration/composer.json if you wanted all sites created from your custom upstream to get that module. Add modules specific to one site to the root-level composer.json file.
- When you run a dashboard one-click update on an IC-based site, then all of the updates from the upstream will be applied, and all of the updates from any of your composer dependencies (e.g. modules you added to your top-level composer.json file) will also be updated. With an IC-based site, you may therefore sometimes have updates available even when your upstream has not been updated.
- You are correct, Pantheon re-uses the same tag (one per environment) to reduce the size of the repository, since old builds are not needed. When you deploy from dev to test, the Pantheon test tag is created in the repository as usual. All deploy tags to test and live are kept forever, just as they have traditionally been for non-Composer-based sites.

**Comment by hanoii** [comment]
@greg-1-anderson thanks a lot! Just one note, on your original note above you instruct to modify things under upstream-configuration. Not sure if you did that because it was meant to be a custom upstream, but worth adding that note to the documentation too.

**Comment by hanoii** [comment]
Oh, and one more question, can I update an existing site in place to IC, or to do that I need it to be generally available?

**Comment by greg-1-anderson** [comment]
Ah, didn't notice that. I will edit and remove that part. In the past, that hack was necessary to revert back to Drupal 8, because the pantheon-upstreams/drupal-project upstream hard-constrained to Drupal 9. These constraints have been loosened, so it is no longer necessary to use an undesirable hack to stay on Drupal 8.

**Comment by greg-1-anderson** [comment]
Also, the documentation PR that you should follow instead of this issue is https://github.com/pantheon-systems/documentation/pull/6145

**Comment by greg-1-anderson** [comment]
> Oh, and one more question, can I update an existing site in place to IC, or to do that I need it to be generally available

You must wait for General Availability before you can upgrade the Mariadb version for an existing site to 10.4. If you want to stay on Drupal 8 with Mariadb 10.0, you can do that now.
