### ISSUE TITLE
Create a Drupal 8 Site From the Command Line - Convert to Drupal 9

### ISSUE THREAD

**Issue by matthewboman** [pantheon-systems/documentation#6262]
Re: [Create a Drupal 8 Site From the Command Line Using Terminus and Drush](https://pantheon.io/docs//guides/drupal8-commandline)

Priority: High

## Issue Description:
This document refers to Drupal 8, which is EOL.

## Suggested Resolution
Retire this guide. 
Create a new guide around creating a Drupal site (non-version-specific) using Terminus and Drush.

**Comment by carolyn-shannon** [comment]
The `site:create` command is also deprecated, so this guide may need to be retired in its entirety.

**Comment by stevector** [comment]
https://pantheon.io/docs/guides/terminus-drupal-site-management is written for Drupal 7. I think the best course of action is updating https://pantheon.io/docs/guides/drupal8-commandline for Drupal 9. I expect that a few of the commands will have to change to account for Integrated Composer and Terminus 3.

I went looking for this issue because this guide came to mind as I thought about what Docs pages will need to be updated for a Terminus 3 announcement.
