### ISSUE TITLE
Migrate to Drupal 9 on Pantheon Doc Update 

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#6332]
Re: [Migrate to Drupal 9 on Pantheon](https://pantheon.io/docs//guides/drupal-9-migration/migrate-manual-d9)

Priority: Low

## Issue Description:

Unnecessary step in "Prepare the Local Environment" section.

Currently, "Prepare the Local Environment" has step 3 as clone your existing site locally; however, this is not necessary.

The section "Create a New Drupal 9 Site and Migrate the Drupal 8 Code" does not explicitly instruct the user to clone the Drupal 9 repository; however, the "Drupal 9" doc it links to does.

## Suggested Resolution

Remove step 3 in "Prepare the Local Environment".

Add text to an existing step in "Create a New Drupal 9 Site and Migrate the Drupal 8 Code" to tell the user to work with the Drupal 9 site that they cloned when they followed the "Drupal 9" doc instructions.

**Comment by EdwardAngert** [comment]
thanks, @greg-1-anderson!
#6381 [removes the line from the partial](https://github.com/pantheon-systems/documentation/pull/6381/files#diff-8b082b00e753657a28743422a1a21d68f4da2ba92524c17f583b34fef7c68770L13) and instead of linking over to our D9 doc for that step, I've adjusted it to be its own section so we can reuse the content in this doc without breaking the reader's focus (+ that's why we made those steps a partial file!)
