### ISSUE TITLE
Unable to Pull down site using LocalDev App

### ISSUE THREAD

**Issue by DixonBrian** [pantheon-systems/documentation#6582]
## Expected behavior
I have installed LocalDev, Lando and Docker. I am able to load the LocalDev Application and sync it with Pantheon using a Machine token for auth. 

## Actual behavior
When I try to "Pull site for Local Development" it makes it partway through the setup before erroring out and rolling back. 
Here is a screenshot of what I am seeing.

![Screen Shot 2021-08-05 at 10 24 04 AM](https://user-images.githubusercontent.com/79521322/128379127-cf85e6d4-8fe4-47e6-9c01-893e9cb1be80.png)

Checking the Error logs for LocalDev I get this error: 

{"level":"warn","message":"problem pulling database from dev!","label":"palmermuseum","timestamp":"2021-08-05T14:23:47.713Z"}
{"level":"error","message":"pulling database from dev errored with: /helpers/auth.sh: line 33: :certs/binding.pem: No such file or directory\n","label":"palmermuseum","timestamp":"2021-08-05T14:23:47.714Z"}

Talking to Pantheon support they think its an authentication issue but not sure what exactly. 

### Steps to reproduce the problem

1. Happens anytime I try to "Pull site for Local Development"

**Comment by EdwardAngert** [comment]
Thanks for filing a Docs issue, @DixonBrian !
Sorry to hear you're having trouble with Localdev.
The closest issue I can find in the documentation is the [Clone Failed Due To Modified .gitignore](https://pantheon.io/docs/guides/localdev/troubleshoot-support#clone-failed-due-to-modified-gitignore) section of the troubleshooting page, but ~I'm not sure that's the issue you've encountered.~ edit: I read through the Support chat and I see you tried that too :-/

In looking through the [issues in the Localdev repo](https://github.com/pantheon-systems/localdev-issues/issues), I found https://github.com/pantheon-systems/localdev-issues/issues/91 . Does that seem like the same kind of issue to you? If it is, I can link to this from there as a +1, and I'll reach out to the Localdev devs to see if they've got any suggestions.

For now, at least until there's a solution we can add to the documentation, I'm closing this issue.

**Comment by DixonBrian** [comment]
Yes the localdev-issue#91 does sound like the same issue. I think you can link them. 
Thanks
