### ISSUE TITLE
Drupal Modules with Known Issues Doc Update 

### ISSUE THREAD

**Issue by matthewboman** [pantheon-systems/documentation#6625]
Re: [Drupal Modules with Known Issues](https://pantheon.io/docs/modules-known-issues)

[Feeds](https://www.drupal.org/project/feeds) (Drupal 8/9, 7 appears to work from the referenced issue)

Priority: Low

## Issue Description:
Feeds can import manually but throws the following error in cron:

`RuntimeException: File <em class="placeholder">/tmp/feeds_http_fetcherOK5Hbi</em> does not exist. in Drupal\feeds\Result\FetcherResult->checkFile() (line 53 of /code/web/modules/contrib/feeds/src/Result/FetcherResult.php).
`

example ticket: [https://pantheon.zendesk.com/agent/tickets/603273](https://pantheon.zendesk.com/agent/tickets/603273) 
open issue in module: [https://www.drupal.org/project/feeds/issues/2912130](https://www.drupal.org/project/feeds/issues/2912130)

## Suggested Resolution
Import feeds manually.
I'm currently testing out patches.
Module maintainers are aware of the issue on Pantheon and Acquia, so hopefully there's some traction for resolving it.

**Comment by EdwardAngert** [comment]
for whoever picks this up
1. doesn't work on load balanced environments (relies on a persistent directory)
1. link to the drupal issue

from @carolyn-shannon (to be reworded in the solution PR):
> It’s an issue w the module running in any load balanced environment. Fyi this is a common issue and is detailed in the doc about temp files, along with one proposed workaround https://pantheon.io/docs/tmp#persistent-temporary-path-workaround. The most common answer (mentioned in this doc) is “have the module maintainer fix the module”.
We caution against putting these files outside the tmp directory because then the files don’t get deleted automatically after the transfer is complete, which can create a very large set of files.
