### ISSUE TITLE
Can the automated preview environment comment include the link(s) to the page(s) that are changed?

### ISSUE THREAD

**Issue by CdrMarks** [pantheon-systems/documentation#7245]
Re: https://github.com/pantheon-systems/documentation/blob/main/tests/lighthouse/createPullRequestComment.js

Priority: Low

## Issue Description

* As a reviewer of PRs in the documentation repository, it's not easy to link directly to the page(s) that were changed in the preview environment.  
* A reviewer need to look a the top comment of the PR to see what pages the author said they were changing, make not of the page's path, browse to the preview environment, and then append the page path to the URL to arrive at the preview of the changed page.

### How will this impact users?

* Makes it easier for reviewers to get to the page(s) on the preview environment to see how the change looks.

## Suggested Resolution

* Modify the automated lighthouse `pullRequestMessage` to include, after the `Preview Environment` link, links to each page that is changed.
* I believe any file changed in [documentation](https://github.com/pantheon-systems/documentation)/[source](https://github.com/pantheon-systems/documentation/tree/main/source)/content/ would result in a linked page being seen in the PR comment.

**Comment by EdwardAngert** [comment]
thanks, @CdrMarks ! this reminds me that the preview thing did used to include a direct link to the changed page(s), and I don't know why or when that stopped

I've added this to our "wish list" jira ticket, [DOC-614](https://getpantheon.atlassian.net/browse/DOC-614) that I'm using to scope the upcoming (and imminent) docs site upgrade and closing the ticket so that we can track the site improvement scope of work in one place
