### ISSUE TITLE
Pantheon WordPress Upstream Doc Update 

### ISSUE THREAD

**Issue by rospencers** [pantheon-systems/documentation#8083]
Re: [Pantheon WordPress Upstream](https://pantheon.io/docs//start-states/wordpress)

Priority: Low/Medium/High (choose one, remove the other options)

High

## Issue Description:

Still no release notes for 17 JAN 2023. Issue 8063 claims this was resolved, but there is definitely no update on the page. See https://github.com/pantheon-systems/documentation/pull/8063

We have a high-visibility critical release and cannot/will not merge undocumented upstream updates. At the same time, the words "fatal error" in the upstream notice are taken very seriously!

## Suggested Resolution

Please publish the promised information that is 9 days late (and counting).

**Comment by whitneymeredith** [comment]
Hello @rospencers ! Thanks for your message. This issue is resolved by [#8063 ](https://github.com/pantheon-systems/documentation/pull/8063). However, we are having technical difficulties with the Docs website. The release notes content may not be visible for a while longer even though it has been merged. We're sorry for any inconvenience this causes.

**Comment by whitneymeredith** [comment]
Closing as this work is done although not yet visible on the website.
