### ISSUE TITLE
Guidance on when to downgrade to a lower site plan to save money

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/documentation#8904]
With the updates to pricing and the improved overages policy, I've seen chatter in community channels about when and how to downgrade to a less expensive plan:

* https://community.pantheon.io/forum/t/cost-analysis-for-march-2024-site-plans-and-overage-protection-changes/172
* https://websites.umich.edu/~markmont/public/pantheon-cost-analysis/

I don't want to overload the already in-progress https://github.com/pantheon-systems/documentation/pull/8886 but maybe we should add a page walking through evaluating whether a downgrade makes sense and how to do it.

**Comment by markmont** [comment]
An updated version of the spreadsheet is now available (version 1.1) at

https://websites.umich.edu/~markmont/public/pantheon-cost-analysis/

If you have version 1.01 or 1.0., please go to the URL above and make a new copy since version 1.1 corrects an error with Basic plan pricing and it should now find the lowest cost plan in all circumstances.

**Comment by stevector** [comment]
overages are suspended currently. I'm going to close this one
