### ISSUE TITLE
Get Support Doc Update 

### ISSUE THREAD

**Issue by ThiagoMouro** [pantheon-systems/documentation#9226]
Re: [Get Support](https://docs.pantheon.io/guides/support/)

Priority: Low/Medium/High (choose one, remove the other options)

## Suggested Resolution

I saw it in wordpress portal, Can I use free plan and force users to log on by saml in this plan?

other problem to report:
This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress. Try [searching](https://wordpress.com/plugins/) for a similar plugin.

**Comment by jazzsequence** [comment]
These questions are specifically about the WP-SAML Auth plugin and not so much about documentation. 

To answer your initial question @ThiagoMouro, there shouldn't be anything functionally restricting you from using the WP-SAML Auth plugin on a site that is not associated with a paid plan on Pantheon. WP-SAML Auth is one plugin of many WordPress plugins that support SAML authentication. 

It's true that the plugin has not received updates in a number of WordPress versions, but that does not necessarily mean it is no longer supported. That plugin has not received a lot of updates primarily because not much in WordPress core has changed that would affect the functionality of the plugin, but if you encounter issues, you are welcome to report them in the [WP-SAML Auth GitHub repository](https://github.com/pantheon-systems/wp-saml-auth/issues) or in [the WordPress.org support forum](https://wordpress.org/support/plugin/wp-saml-auth/) or use a different SAML authentication plugin (like the [miniOrange SAML plugin](https://wordpress.org/plugins/miniorange-saml-20-single-sign-on/)).
