### ISSUE TITLE
Add D8 instructions to Export an Existing Drupal Site

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/documentation#926]
## Description
If the process is different than Drupal 7, create a D8 version similar to:
https://pantheon.io/docs/articles/sites/migrate/export-an-existing-drupal-site/

## Outline
1. Intro
2. Prepare Your Site for Export
3. Create Archive (using Backup & Migrate, Drush, manually )

## Expected Audience
D8 users

## Path
(/docs/articles/drupal/8

**Comment by bmackinney** [comment]
The process shouldn't be different enough to warrant another doc, rather a section in the current doc.

**Comment by JessiFischer** [comment]
Trying to be meticulous and run through the manual archive creation process. Directory structure between the two is pretty similar (though there's all the new vendor stuff like Symfony) but I need to be sure an archive of a running site will have the same process. Currently wrestling with vagrant as I haven't used it since some major OS upgrades. Wiping and reinstalling at this point and hope to get this done by the end of the week.

**Comment by JessiFischer** [comment]
Running through documentation for D*, backup and migrate has a D8 compatible version and the drush archive-dump command will also work: 

https://www.drupal.org/node/189065/release

http://drushcommands.com/drush-8x/core/archive-dump/

Nothing different here, tools and instructions are the same. The one thing that is a bit different is the directory structure: https://gist.githubusercontent.com/JessiFischer/4b0be915ffc52aa2904a/raw/9fed03c76e3bb6a5a20c65ce833f3c15e7b4083b/code_dir

**Comment by nataliejeremy** [comment]
This doc doesn't need to be updated..closing this issue.
