### ISSUE TITLE
Update to Private Files doc: configuring private files in Drupal 8

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/documentation#937]
See pantheon-systems/drops-8#69

**Comment by rachelwhitton** [comment]
@greg-1-anderson should this be a new doc, or an update to the existing [Private Files](https://pantheon.io/docs/articles/drupal/private-files/) doc? @bmackinney what do you think?

Here's what I have so far:
1. Switch to SFTP mode
2. Create `sites/default/files/private` dir if none exists
3. Add `$settings['file_private_path'] = 'sites/default/files/private';` to `settings.pantheon.php`
4. Clear cache 
5. From **Administration** >> **Configuration** >> **Media**, select **Private local files served by Drupal** for **Default download method**.

**Comment by greg-1-anderson** [comment]
See https://github.com/pantheon-systems/drops-8/issues/69#issuecomment-140564666 and https://github.com/pantheon-systems/drops-8/issues/69#issuecomment-140769445

We could prepopulate settings.php with `$settings['file_private_path'] = 'sites/default/files/private';`; since this is the only valid value for this setting, it would reduce the chance for error and make things easier on the user.

**IMPORTANT NOTE:** `settings.pantheon.php` is for Pantheon's use only.  Any documentation that instructs the user to configure settings should tell them to modify `settings.php`.  Modifying settings.pantheon.php is not allowed, as this file might change in a future release, which would cause conflicts on update.

**Comment by rachelwhitton** [comment]
We don't currently have documentation on modifying `settings.pantheon.php` but thinking we should warn against it preemptively. #964 has been created to add this note in the docs. 

If there are no objections, I'm planning to add D8 content to our existing doc, [Private Files](https://pantheon.io/docs/articles/drupal/private-files/). 

Labeled as pri:high to close major issue pantheon-systems/drops-8#69

@greg-1-anderson +1 to prepopulate settings.php with `$settings['file_private_path'] = 'sites/default/files/private';` - especially since it's the only valid value. Is it possible to create the `sites/default/files/private` directory upon installation? So that **Private local files served by Drupal** is an option straight away?

**Comment by greg-1-anderson** [comment]
Yes, I will prepopulate the setting value and create the directory in advance. The only thing the user will need to do is visit the admin page and change the radio button setting to "private".

**Comment by greg-1-anderson** [comment]
Oh, and I shouldn't say it's the only *valid* value, it's the only *safe* value.  :)

**Comment by rachelwhitton** [comment]
Sweet! Thanks @greg-1-anderson :tada:
